### ISSUE TITLE
Azure OpenAI 报错

### ISSUE THREAD

**Issue by fengjisheng** [Calcium-Ion/new-api#101]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√] 我已确认我已升级到最新版本
+ [√] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接入Azure OpenAI 一直报错.

**相关截图**
![DNT%$O6(8%_{4PD837`55RA](https://github.com/Calcium-Ion/new-api/assets/7992420/c7cd2116-f3da-4412-a50e-e0bcd247855b)
![$71QQ3%GSN$U4WHSYUKVXL5](https://github.com/Calcium-Ion/new-api/assets/7992420/3aae06f5-b463-4ce8-9011-2591fb719a7a)

**Comment by yinqf** [comment]
我升级之后，也发现了，是重定向功能失效了

**Comment by hcppxgit** [comment]
同样的问题，我也报错：错误：status code 404: Resource not found。我接口和密钥拿到别的地方测试是正常的。看楼上说重定向报错，删除了重定向问题依旧。

**Comment by Calcium-Ion** [comment]
调用没问题，是测试有问题
