### ISSUE TITLE
是否可以添加一个允许用户单独设置预警额度（额度不足发邮件）的选项？

### ISSUE THREAD

**Issue by shyboy** [Calcium-Ion/new-api#106]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
每个用户的消耗不一样，充值的额度不一样，比如那种5刀花一个月的和5000刀一个月的用户，需要提前预警的额度不一样。请问可否添加功能允许用户单独设置预警额度大小，或者管理单独给不同客户设置预警额度大小？

Thanks♪(･ω･)ﾉ

**Comment by hcppxgit** [comment]
没啥用的功能，余额少的管他干嘛，用量少说明他可用可不用，用不了了他们自己就会知道充值
