### ISSUE TITLE
BUG: 渠道管理乱序或重复的问题

### ISSUE THREAD

**Issue by ClarenceDan** [Calcium-Ion/new-api#11]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
1. 渠道管理由于按优先级排列，存在乱序，翻页时概率出现之前的渠道
2. 点击按ID排序后会出现重复的渠道名

**复现步骤**
1. 点击渠道管理，翻页
2. 点击按ID排序

**预期结果**
通常情况下会出现重复的渠道ID，如果没出现，多翻几页再点击按ID排序就会出现
希望修复该BUG，并按照渠道ID排序渠道，因为批量添加渠道时，优先级通常都是相同的，会导致乱序的情况。

**相关截图**
![d81545eca4870b2489168a85e4d8d29f](https://github.com/Calcium-Ion/new-api/assets/48417261/e5b78491-3267-481e-ab82-5540b3532699)

如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
最新版添加了id排序
