### ISSUE TITLE
0.1.x升级0.2.x数据库问题

### ISSUE THREAD

**Issue by hehan-wang** [Calcium-Ion/new-api#110]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
2024/03/11 10:51:24 /build/model/main.go:96 Error 1170: BLOB/TEXT column 'key' used in key specification without a key length
[1.493ms] [rows:0] ALTER TABLE `channels` MODIFY COLUMN `key` longtext NOT NULL
[FATAL] 2024/03/11 - 10:51:24 | [failed to initialize database: Error 1170: BLOB/TEXT column 'key' used in key specification without a key length] 

已经删除执行索引sql，依然报错
当前channel表sql
```sql
CREATE TABLE `channels` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `type` bigint DEFAULT '0',
  `key` varchar(191) NOT NULL,
  `open_ai_organization` longtext,
  `status` bigint DEFAULT '1',
  `name` varchar(191) DEFAULT NULL,
  `weight` bigint unsigned DEFAULT '0',
  `created_time` bigint DEFAULT NULL,
  `test_time` bigint DEFAULT NULL,
  `response_time` bigint DEFAULT NULL,
  `base_url` varchar(191) DEFAULT '',
  `other` longtext,
  `balance` double DEFAULT NULL,
  `balance_updated_time` bigint DEFAULT NULL,
  `models` longtext,
  `group` varchar(64) DEFAULT 'default',
  `used_quota` bigint DEFAULT '0',
  `model_mapping` varchar(1024) DEFAULT '',
  `priority` bigint DEFAULT '0',
  `auto_ban` bigint DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `idx_channels_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=3709 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
备份一下channels表的数据，然后删除channels表，让new api重新生成吧

**Comment by daggeryu** [comment]
drop index idx_channels_key on channels;
ALTER TABLE channels
    MODIFY `key` longtext not null,
    ADD INDEX idx_channels_key (`key`(255));
