### ISSUE TITLE
gpt的 `generations` 接口

### ISSUE THREAD

**Issue by bincooo** [Calcium-Ion/new-api#115]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
劳请实现gpt的 `/v1/images/generations` 绘画接口，感谢🙏

**复现步骤**

**预期结果**
<img width="295" alt="Screenshot 2024-03-13 at 22 12 54" src="https://github.com/Calcium-Ion/new-api/assets/36452456/c63f4af9-57b6-449b-822c-e884576c8498">
<img width="370" alt="Screenshot 2024-03-13 at 22 13 18" src="https://github.com/Calcium-Ion/new-api/assets/36452456/a47727ee-ece1-41b1-a0c6-f581c647e1ab">

**Comment by Calcium-Ion** [comment]
<img width="804" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/61247483/40531925-0f21-4dc5-b816-c3c5af83c66f">
是不是您自己的渠道有问题，这个功能是没问题的

**Comment by bincooo** [comment]
哦，抱歉
确实是渠道问题
