### ISSUE TITLE
支持新模型 Anthropic Claude 3.0 Haiku

### ISSUE THREAD

**Issue by ckt1031** [Calcium-Ion/new-api#116]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

Anthropic 最近发布了最小、最快的 Claude 3.0 Haiku: `claude-3-haiku-20240307`

https://docs.anthropic.com/claude/docs/models-overview

![image](https://github.com/Calcium-Ion/new-api/assets/65409152/a48f2f94-9e8c-4c2c-ba2c-7f962b95f405)

**Comment by Calcium-Ion** [comment]
可以手动加一下自定义模型claude-3-haiku-20240307，倍率0.125
