### ISSUE TITLE
渠道、用户管理、日志页面增加并记住可显示的项目条数

### ISSUE THREAD

**Issue by Ruler27** [Calcium-Ion/new-api#118]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

渠道页面可以显示最多 100 条/页，但是不能记住设置，渠道多了以后不方便查看，每次进去都得去右下角点一下。
然后日志和用户管理页面也可以增加这个选项。

**应用场景**

记录查看方便些。

**Comment by Raymond0Hui** [comment]
希望用户管理页面也可以增加这个选项

**Comment by Raymond0Hui** [comment]
用户管理页面也能麻烦改一下吗
