### ISSUE TITLE
易支付不支持二级路径/xpay/epay/submit.php，希望支持二级路径

### ISSUE THREAD

**Issue by homestoo** [Calcium-Ion/new-api#119]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支付地址填写https://xxxx.xxxx.com/xpay/epay时，支付跳转不会跳转到https://xxxx.xxxx.com/xpay/epay/submit.php而是跳转到https://xxxx.xxxx.com/submit.php
希望能支持二级路径/xpay/epay/submit.php跳转

**应用场景**
<img width="515" alt="22" src="https://github.com/Calcium-Ion/new-api/assets/95828857/05fef2c4-6742-453d-9998-15116b7d3e92">

<img width="638" alt="2" src="https://github.com/Calcium-Ion/new-api/assets/95828857/5bd8729f-5fa3-4af5-93dc-631dbb84f445">

**Comment by wxy545812093** [comment]
你这个问题跟 new-api 有啥关系？ 要治本就去支付项目，在nginx的vhost配置中 将 root 指向你的 二级目录.(apache的我不知道了，但原理是一样的。我几百年都没用过apache了)
![000](https://github.com/Calcium-Ion/new-api/assets/4502958/65afdcd3-238a-4409-b915-8fb951d6a948)

**Comment by wxy545812093** [comment]
顺便问下，你看是不是也把你的支付系统源码发我一套。有问题我来解决，有锅我来背，你安逸的很。
