### ISSUE TITLE
怎么热重载开发？

### ISSUE THREAD

**Issue by 14790897** [Calcium-Ion/new-api#120]

**Comment by Calcium-Ion** [comment]
https://github.com/cosmtrek/air
请参考这个项目

**Comment by 14790897** [comment]
前端也可以吗

**Comment by 14790897** [comment]
![image](https://github.com/Calcium-Ion/new-api/assets/121866954/eed3a3bf-291f-4631-bcdd-ffa99cb86822)

**Comment by 14790897** [comment]
🤷‍♂️

**Comment by Calcium-Ion** [comment]
项目支持前后端分离，所以没必要在开发的时候打包进embed，直接在项目web文件夹下使用npm run start开发

**Comment by 14790897** [comment]
好好好

**Comment by 14790897** [comment]
怎么没有.air.toml的配置？

**Comment by 14790897** [comment]
还是不会前端热重载，要修改main.go吗

**Comment by 14790897** [comment]
windows是不是不适合开发go？

**Comment by 14790897** [comment]
这个前端的格式有配置文件吗？我的vs code它自动格式化和原来格式不匹配

**Comment by 14790897** [comment]
> 项目支持前后端分离，所以没必要在开发的时候打包进embed，直接在项目web文件夹下使用npm run start开发

哥，跨域怎么解决的？

**Comment by 14790897** [comment]
哥，在吗，急
