### ISSUE TITLE
添加Perplexity支持

### ISSUE THREAD

**Issue by 1PercentSync** [Calcium-Ion/new-api#121]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
目前把perplexity的api当作openai api的自定义渠道添加会报错404，原因是perplexity没有v1段
请求的是https://api.perplexity.ai/chat/completions
具体api文档https://docs.perplexity.ai/reference/post_chat_completions
**应用场景**

**Comment by 1PercentSync** [comment]
请求的具体格式是和openai兼容的

**Comment by Calcium-Ion** [comment]
最新提交添加了perplexity支持，可以测试一下

**Comment by 1PercentSync** [comment]
> 最新提交添加了perplexity支持，可以测试一下

sorry我除了docker以外都不太好测，要不我给你个key测试？
