### ISSUE TITLE
侧边栏聚焦问题

### ISSUE THREAD

**Issue by 13531446481** [Calcium-Ion/new-api#123]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
+    版本为v0.2.0.2
当点击首页的点击跳转链接到侧边栏的聊天指向的聊天界面（如nextweb的界面）时，侧边栏focus在首页，不是focus在“聊天”。例如：首页有个叫做开始聊天的按钮，url指向：该项目域名/chat，点击按钮，此时确实会跳转到chat的界面，但是侧边栏还停留到首页

**相关截图**
![1710661372633](https://github.com/Calcium-Ion/new-api/assets/125166290/5aea909a-e2a0-45af-96ab-f50a77790cae)

**Comment by 13531446481** [comment]
是项目有bug还是我应该调整一下我的跳转的逻辑

**Comment by Calcium-Ion** [comment]
刷新之后确实会导致聚焦到首页

**Comment by 13531446481** [comment]
还是没有解决哦，我更新到了最新版本后仍然存在这个问题

**Comment by 13531446481** [comment]
> 刷新之后确实会导致聚焦到首页


还是没有解决哦，我更新到了最新版本后仍然存在这个问题

**Comment by Calcium-Ion** [comment]
你构建的吗？最新是哪个最新

**Comment by 13531446481** [comment]
> 你构建的吗？最新是哪个最新

解决啦，谢谢姐姐，更新到v0.2.0.3-alpha.2就好了
