### ISSUE TITLE
智谱 ChatGLM 调用问题

### ISSUE THREAD

**Issue by magicdmer** [Calcium-Ion/new-api#124]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
调用智谱 ChatGLM模型时，提示如下错误：
```
[1214][top_p参数非法。请检查文档。]
```
我是从最新的one-api缓过来的，one-api是正常的

**复现步骤**
1. new-api 渠道添加 智谱 ChatGLM
2. 使用chatgpt-web，选择glm-4模型进行访问

**预期结果**
应该正确调用回复

**相关截图**
![test](https://github.com/Calcium-Ion/new-api/assets/5556368/a2ab9cea-d8aa-4b83-aa73-2970b72256fe)

**Comment by Calcium-Ion** [comment]
你使用的new api版本是什么

**Comment by magicdmer** [comment]
> 你使用的new api版本是什么

https://github.com/songquanpeng/one-api/issues/1045
刚翻了一下oneapi的issue，发现是最近几个星期修复的，我是最新的release，0.6.2

**Comment by Calcium-Ion** [comment]
已修复

**Comment by magicdmer** [comment]
> 已修复

我看了一下one-api的issue，Temperature这个字段也有一样的问题，是否需要也修复一下？

**Comment by Calcium-Ion** [comment]
如果不影响使用的情况下，不能算是bug，我认为本来top_p也不应该去修复，应该让下游应用适配

**Comment by magicdmer** [comment]
> 如果不影响使用的情况下，不能算是bug，我认为本来top_p也不应该去修复，应该让下游应用适配

但是one-api目的不就是要所有支持模型兼容openai的调用，这样第三方客户端不需要修改就能调用各种模型，还是希望改一下

**Comment by magicdmer** [comment]
还有个蛮奇怪的，我本来准备更新docker，发现action里面只有arm64的，没看到amd64的最新docker
**补充：** 好了，我自己fork了一个repo，同步了一下one-api的修改，然后由于我修改了docker制作yml，所以没法create pull了，感谢创建这么好用的工程
