### ISSUE TITLE
添加渠道groq时代理地址报错

### ISSUE THREAD

**Issue by huawuhen** [Calcium-Ion/new-api#126]
测试报错：错误：status code 404: Unknown request URL: POST /openai/v1/v1/chat/completions. Please check the URL for typos, or see the docs at https://console.groq.com/docs/
代理填写官方给的 https://api.groq.com/openai/v1
自定义模型mixtral-8x7b-32768时兼容openai，已在nextchat中测试成功。

**Comment by Calcium-Ion** [comment]
代理填写 https://api.groq.com/openai 试试

**Comment by huawuhen** [comment]
> 代理填写 https://api.groq.com/openai 试试

错误：status code 404: The model `gpt-3.5-turbo` does not exist or you do not have access to it.

**Comment by Calcium-Ion** [comment]
测试功能现在肯定是不兼容的，这样应该是可以对接groq的模型了

**Comment by huawuhen** [comment]
> 测试功能现在肯定是不兼容的，这样应该是可以对接groq的模型了

明白了，测试功能默认指定了gpt-3.5-turbo模型。谢谢
