### ISSUE TITLE
关于调用googleapi的字体链接导致后台的首次加载缓慢问题报告

### ISSUE THREAD

**Issue by sunsky89757** [Calcium-Ion/new-api#130]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
大佬，咱就说这个google家族的字体api链接可否去掉换成其它的国内容易加载的？我一直怀疑是数据库加载慢，后来才发现罪魁祸首是这个css类的文件，因为调用了googleapi，所以没有开t的情况下，基本上打开后台都是30秒起步。
大佬辛苦了！

**复现步骤**

**预期结果**
不用谷歌字体的api

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/113254524/fd20ade2-89c2-42c5-80b7-42938d23360a)
![image](https://github.com/Calcium-Ion/new-api/assets/113254524/89518b10-bb55-4c8f-af41-e17267857f5c)

**Comment by hcppxgit** [comment]
原来是这个原因，怪不得我有时候打开要等半天转圈圈
