### ISSUE TITLE
v0.2.1.0-alpha.5版本非流用不了了

### ISSUE THREAD

**Issue by sunsky89757** [Calcium-Ion/new-api#139]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
v0.2.1.0-alpha.5版本模型的非流请求用不了了
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/113254524/20bf5340-5328-4e95-8a7e-876eea3bb9a0)
![image](https://github.com/Calcium-Ion/new-api/assets/113254524/7183248c-66a7-41e1-8bb1-e1096fa5a75f)

**Comment by Calcium-Ion** [comment]
调用的模型，选择的渠道是什么

**Comment by Calcium-Ion** [comment]
测试一下v0.2.1.0-alpha.6

**Comment by sunsky89757** [comment]
gpt-3.5-turbo，这个模型，好的，晚点我试试

**Comment by xiaozhang959** [comment]
请问楼主您的问题解决了吗？   我用docker部署的最新版，使用非流式访问将会返回空响应，但是使用流式访问又可以。
![图片](https://github.com/Calcium-Ion/new-api/assets/89305607/5a666ae2-c9cd-4007-97f7-3786c953f861)
![图片](https://github.com/Calcium-Ion/new-api/assets/89305607/4f2640a6-0b8c-41fc-a19e-d87e73280960)

**Comment by sunsky89757** [comment]
> 请问楼主您的问题解决了吗？ 我用docker部署的最新版，使用非流式访问将会返回空响应，但是使用流式访问又可以。 ![图片](https://private-user-images.githubusercontent.com/89305607/316356263-5a666ae2-c9cd-4007-97f7-3786c953f861.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjgxMjUsIm5iZiI6MTcxMTMyNzgyNSwicGF0aCI6Ii84OTMwNTYwNy8zMTYzNTYyNjMtNWE2NjZhZTItYzljZC00MDA3LTk3ZjctMzc4NmM5NTNmODYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAwNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNDdmMWEwZWY1NjMxODA1MjhhOWNkYzljZGJiNjJlZTM1ZGNkZGIxZTJiYTQ1MjA5ZDc3ZTNkNmRmZWE2ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWpS4YAdKBI2OsxXQsnO63Mrgn_99yi0kCeUk7QOb18) ![图片](https://private-user-images.githubusercontent.com/89305607/316356270-4f2640a6-0b8c-41fc-a19e-d87e73280960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjgxMjUsIm5iZiI6MTcxMTMyNzgyNSwicGF0aCI6Ii84OTMwNTYwNy8zMTYzNTYyNzAtNGYyNjQwYTYtMGI4Yy00MWZjLWExOWUtZDg3ZTczMjgwOTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDAwNTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MDgzYjdjYzNhYmU4MTI4YTExMWE3OTU0NWY2YjQ1NjA2MWEyOTNmOTU5MjUwNTljZjY1MWRlMjRjYmEyNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MrnaNLDlA-bfrofTmeTNjIDBI01I-Q0jb3oHGOYTlfs)

已经可以了，你的可能是上游中转服务商的问题
