### ISSUE TITLE
模型消耗与设置不符

### ISSUE THREAD

**Issue by 13531446481** [Calcium-Ion/new-api#143]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我用了两个服务器a,b，部署两个new-api项目，其中b项目的数据库用的是a服务器上的数据库，我在项目b上设置了模型倍率，当我使用项目b的接口调用模型的时候，并没有按照设置中的固定倍率去扣费，而是按照最原始的token乘倍率去扣费的
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/125166290/159e53b7-3e49-4687-a80e-b00d22299382)
![image](https://github.com/Calcium-Ion/new-api/assets/125166290/67abf8cf-e51f-4d21-90e9-db61c0971fa6)

**Comment by Calcium-Ion** [comment]
尝试使用v0.2.1.0-alpha.14

**Comment by 13531446481** [comment]
> 尝试使用v0.2.1.0-alpha.14

问题已解决
