### ISSUE TITLE
当首页放的是ip+端口，不是域名时，不会渲染网页内容

### ISSUE THREAD

**Issue by 13531446481** [Calcium-Ion/new-api#147]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当首页放的是ip+端口，不是域名时，不会渲染网页内容
**复现步骤**

**预期结果**

**相关截图**
![9c9af6981cb63810a84b76ebaf38589](https://github.com/Calcium-Ion/new-api/assets/125166290/daabd9ac-4644-464f-9346-a2b176f8c6d7)
![b05343df7333d2e52320231cf295912](https://github.com/Calcium-Ion/new-api/assets/125166290/33616c96-4c48-4397-81bf-7a653fef026d)

**Comment by Calcium-Ion** [comment]
渲染地址必须以 https:// 开头
