### ISSUE TITLE
MySQL数据库连接部署的New-api经常碰到Cannot read properties of undefined (reading 'map') 这个错误，原因不明

### ISSUE THREAD

**Issue by sunsky89757** [Calcium-Ion/new-api#148]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
MySQL数据库连接部署的New-api经常碰到Cannot read properties of undefined (reading 'map') 这个错误，原因不明；目前并不影响使用。
**复现步骤**
有一点时间没有访问后台后再进入访问，虽然处于登录状态，但是打开“渠道”菜单会报这个弹窗错误。
**预期结果**

**相关截图**

**Comment by sunsky89757** [comment]
![111](https://github.com/Calcium-Ion/new-api/assets/113254524/387c1341-70f0-4b4c-93d4-25f087835229)

**Comment by Calcium-Ion** [comment]
登陆失效导致
