### ISSUE TITLE
模型重定向功能一直不正常，辛苦修复

### ISSUE THREAD

**Issue by huawuhen** [Calcium-Ion/new-api#149]
模型重定向鼓捣了几天都不行，开始以为自己配置错了，后来one-api那里同样的配置就好了。麻烦修复下，或者给个正确的配置方法。

**Comment by Calcium-Ion** [comment]
你更新到最新版了吗？配置截图以及无法使用的复现截图也没有？

**Comment by kuangxiaoye** [comment]
现在失败重试完全G，307

**Comment by huawuhen** [comment]
[![pFIcum6.jpg](https://s21.ax1x.com/2024/03/27/pFIcum6.jpg)](https://imgse.com/i/pFIcum6)
报错：
[![pFIcK0K.jpg](https://s21.ax1x.com/2024/03/27/pFIcK0K.jpg)](https://imgse.com/i/pFIcK0K)
