### ISSUE TITLE
根据上游渠道和key自动填充模型

### ISSUE THREAD

**Issue by kokojacket** [Calcium-Ion/new-api#150]
希望能增加，根据上游渠道地址和apikey，自动检测并填充模型。

**Comment by Calcium-Ion** [comment]
有应用场景吗

**Comment by kokojacket** [comment]
在添加一些三方api的时候，每家的api支持的模型数量都不相同。基本都需要对照第三方文档地址一个个去填入。
后面部署了[chatnio](https://github.com/Deeptrain-Community/chatnio)这个项目，发现他们实现了自动适应上游模型。感觉很方便，所以建议一下。要是太麻烦大佬就不要理会我。😄

**Comment by candies404** [comment]
> 有应用场景吗

https://github.com/ai365vip/chat-api/issues/35 抄一下😆
