### ISSUE TITLE
可更改支付界面充值单位，一个是美元为单位，一个是没单位（以token为单位）

### ISSUE THREAD

**Issue by 13531446481** [Calcium-Ion/new-api#152]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
现有的账单界面支持按照token的显示方式，但是支付界面只有美元为单位的，没有无单位的（以token为单位显示的），请求加一个以token为单位的选项
**应用场景**
![b25ea4b8806cf8c8ba71d676889ee5b](https://github.com/Calcium-Ion/new-api/assets/125166290/6470c5fc-dca1-4285-99dc-85c276fbd24a)
![596934efadeef63fec1bca80e495c01](https://github.com/Calcium-Ion/new-api/assets/125166290/44c8d6ec-2555-455e-8132-af72c939a1d4)

**Comment by Calcium-Ion** [comment]
v0.2.1.0-alpha.24已支持，有bug及时反馈
