### ISSUE TITLE
向量模型使用报错

### ISSUE THREAD

**Issue by longkun0203** [Calcium-Ion/new-api#157]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接入渠道以后，使用模型text-embedding-ada-002提示解析问题失败（知识库系统报错提醒）。
**复现步骤**
不通过new api中转，直接使用上游地址则正常，上游使用的是shll api，截图为知识库报错提示，仅供参考。
**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/55705293/5c2beb6e-1d47-49a3-b09e-db8eb51875dc)

**Comment by Calcium-Ion** [comment]
你更新到最新版了没？

**Comment by longkun0203** [comment]
> 你更新到最新版了没？

更新了

**Comment by longkun0203** [comment]
> 你更新到最新版了没？

重新搭建的还是
