### ISSUE TITLE
为openai的函数调用加上计费避免逃费问题

### ISSUE THREAD

**Issue by Coder-Wjt** [Calcium-Ion/new-api#158]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在openai的函数调用（function call）功能加上token计费功能，避免逃费问题
**应用场景**

**Comment by Calcium-Ion** [comment]
最新版已加入函数计费
