### ISSUE TITLE
希望能够添加码支付功能

### ISSUE THREAD

**Issue by duansix** [Calcium-Ion/new-api#16]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
对接码支付平台 
**应用场景**
易支付容易跑路 码支付更实用一些

**Comment by haibinml** [comment]
易支付插件很多你直接自己再搭建一个易支付得了

**Comment by Glamorous98** [comment]
码支付现在能用你可以试试

**Comment by Glamorous98** [comment]
> 码支付现在能用你可以试试

pay.uukk.uk

**Comment by Glamorous98** [comment]
码支付现在能用
你可以试试
pay.uukk.uk

**Comment by jachin113** [comment]
> 代码支付现在可以用 您尝试 pay.uukk.uk

直接可以配置到new api的平台里面去吗

**Comment by jachin113** [comment]
> 易支付插件很多你自己再搭建一个易支付得了

有易支付源码吗
