### ISSUE TITLE
对接上游MJ功能，失败了没有触发补偿机制

### ISSUE THREAD

**Issue by weikecloud** [Calcium-Ion/new-api#163]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述&&复现步骤**
有两套一样的new-api系统，分别是系统A和系统B，系统A对接了Midjourney并且能正常触发消耗和补偿功能，系统B将系统A作为上游，配置了Midjourney渠道，能正常消耗，但是遇到失败，系统B没有触发补偿功能

**预期结果**
当配置了上游Midjourney，绘画失败后触发补偿功能

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/36788191/07c74d04-363b-43e7-9236-fd4ee277f4f8)
![image](https://github.com/Calcium-Ion/new-api/assets/36788191/a9330502-6a9a-4a5b-b028-dd8935e63c35)

**Comment by longkun0203** [comment]
我也碰到了

**Comment by weikecloud** [comment]
我发现了是在midjourney触发补偿机制的时候少了判断 task.Progress == "100%" && task.Status == "FAILURE"，这个也是失败需要触发补偿机制
