### ISSUE TITLE
建立渠道出现422错误

### ISSUE THREAD

**Issue by AthanaD** [Calcium-Ion/new-api#164]
![image](https://github.com/Calcium-Ion/new-api/assets/125889247/52e92c51-0716-4b78-8af7-dcfe1f296732)
![image](https://github.com/Calcium-Ion/new-api/assets/125889247/eaaa0a14-44b2-4b26-8456-481f191906ce)

**Comment by Calcium-Ion** [comment]
你这个模型到底是什么东西。都不一定能适配
