### ISSUE TITLE
docker部署启动报错

### ISSUE THREAD

**Issue by DC925928496** [Calcium-Ion/new-api#166]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
docker启动报错，明明之前好的，突然就这样了

[SYS] 2024/03/30 - 10:03:16 | New API v0.2.1.0-alpha.19 started 
[SYS] 2024/03/30 - 10:03:16 | SQL_DSN not set, using SQLite as database 
[SYS] 2024/03/30 - 10:03:16 | database migration started 
[SYS] 2024/03/30 - 10:03:16 | database migrated 
[SYS] 2024/03/30 - 10:03:16 | REDIS_CONN_STRING not set, Redis is not enabled 
[SYS] 2024/03/30 - 10:03:16 | initializing token encoders 
[SYS] 2024/03/30 - 10:03:16 | 正在更新数据看板数据... 
[SYS] 2024/03/30 - 10:03:16 | 保存数据看板数据成功，共保存0条数据 
[FATAL] 2024/03/30 - 10:03:16 | [failed to get gpt-3.5-turbo token encoder: Get "https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken": dial tcp: lookup openaipublic.blob.core.windows.net on 192.168.1.1:53: no such host] 

**复现步骤**
docker run --name new-api -d --restart always -p 3030:3000 -e TZ=Asia/Shanghai -v /home/new-api:/data calciumion/new-api:latest

**预期结果**
docker启动失败

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/29574036/8b94763b-9a52-4d32-8d4b-c767b48b3ab3)

**Comment by weikecloud** [comment]
你数据库连不上

**Comment by DC925928496** [comment]
> 你数据库连不上

sqllite不是自带的吗，我重新拉取了镜像的

**Comment by weikecloud** [comment]
那你这也不算是报错，项目有正常运行吧？要么就是不支持sqllite，需要mysql

**Comment by DC925928496** [comment]
> 那你这也不算是报错，项目有正常运行吧？要么就是不支持sqllite，需要mysql

docker服务停了，然后一直重启，但是我之前oneapi能启动的，换过来就不行了，然后换回oneapi也不行了，就很奇怪

**Comment by weikecloud** [comment]
重新部署吧，不干净了

**Comment by DC925928496** [comment]
> 重新部署吧，不干净了

我把文件和镜像都删掉了重新下也不行。。。还要咋办？

**Comment by weikecloud** [comment]
是不是端口冲突了，你把整个日志截图看看

**Comment by DC925928496** [comment]
> 是不是端口冲突了，你把整个日志截图看看

整个日志就是一直循环我复制这段内容，一直重启

**Comment by weikecloud** [comment]
怎么感觉是在访问了gpt3.5出错导致循环呢

**Comment by DC925928496** [comment]
> 怎么感觉是在访问了gpt3.5出错导致循环呢

看报错是这个逻辑，但是很奇怪我全新的镜像为啥会有这个，哪里没删除干净吗，而且3.5访问的还是我局域网，更奇怪了

**Comment by Calcium-Ion** [comment]
是你服务器的网络问题，和new无关

**Comment by bearfishops** [comment]
机器无法通信公网的情况下，怎么解决的，报错无法访问https://openaipublic.blob.core.windows.net/encodings/cl100k_base.tiktoken，导致启动失败

**Comment by Ssiswent** [comment]
<img width="631" alt="Image" src="https://github.com/user-attachments/assets/a567ba9a-fd06-4ca5-9eda-5816c8ae1ac3" />
一样的情况，请问怎么解决。。。
