### ISSUE TITLE
更新后模型倍率出现问题

### ISSUE THREAD

**Issue by 13531446481** [Calcium-Ion/new-api#180]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在更新alpha25之前，出现数据库结构被破坏，然后点击修复，再更新到25，倍率会有问题
![image](https://github.com/Calcium-Ion/new-api/assets/125166290/671865fb-18c7-4a2d-83d3-44aab4594d48)
![image](https://github.com/Calcium-Ion/new-api/assets/125166290/24a79079-8c65-4035-8e9d-524ea56389bd)

**Comment by Calcium-Ion** [comment]
当前模型价格设置只支持 "/v1/chat/completions" 调用的模型

**Comment by 13531446481** [comment]
那这个37.5k是怎么来的，或者说有没有别的方法调整dalle的价格

**Comment by Calcium-Ion** [comment]
只能调整倍率，16倍是官方价格，0.04刀一张，换算就是20000，你的37500是（20000/16）*30得来的

**Comment by 13531446481** [comment]
搞定啦，谢谢姐姐。默认倍率是30，按照比例调整模型倍率就好了。
