### ISSUE TITLE
接口 /v1/embeddings 仅支持string，不支持数组

### ISSUE THREAD

**Issue by TimchaStudio** [Calcium-Ion/new-api#189]
```
let chunks: FileItemChunk[] = []

switch (fileExtension) {
  case "csv":
    chunks = await processCSV(blob)
    break
  case "json":
    chunks = await processJSON(blob)
    break
  case "md":
    chunks = await processMarkdown(blob)
    break
  case "pdf":
    chunks = await processPdf(blob)
    break
  case "txt":
    chunks = await processTxt(blob)
    break
  default:
    return new NextResponse("Unsupported file type", {
      status: 400
    })
}

let embeddings: any = []

const openai = new OpenAI({
  apiKey: profile.openai_api_key || "",
  baseURL: "https://new-api.com/v1"
})

const response = await openai.embeddings.create({
  model: "text-embedding-3-small",
  input: chunks.map(chunk => chunk.content)
})
```
其中input: chunks.map(chunk => chunk.content) ，chunk 是文件处理后字符串数组。
baseURL  为官方接口 https://api.openai.com/v1 时文件能成功上传并响应
baseURL 为one-api接口https://new-api.com/v1 时，文件上传返回以下错误
```
Failed to upload. JSON object requested, multiple (or no) rows returned
```
似乎接口只支持字符串，不支持数组。

https://platform.openai.com/docs/api-reference/embeddings/create

**Comment by Calcium-Ion** [comment]
不方便统计token数量

**Comment by TimchaStudio** [comment]
项目有对文件进行处理，把文件处理成为 chunks 数组。我查阅一下官方接口，是支持 字符串 和 数组 作为输入：https://platform.openai.com/docs/api-reference/embeddings/create 。

const response = await openai.embeddings.create({
  model: "text-embedding-3-small",
  input: chunks.map(chunk => chunk.content)
})

输入数组，new-api 无法处理。

**Comment by Calcium-Ion** [comment]
现在最新版应该已经修复数组的问题了，你试一下

**Comment by TimchaStudio** [comment]
可以了。new-api 接口 /v1/embeddings 支持数组。 感谢作者大大。
