### ISSUE TITLE
数据看板优化建议

### ISSUE THREAD

**Issue by SunnyGPT** [Calcium-Ion/new-api#190]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
1、圆状图+柱状图 点击模型名称 隐藏 该模型，改成 点击后隐藏其他模型，只显示该模型。
2、圆状图与柱状图的模型色块保持一致
3、点击动作同时对两个图生效
4、圆状图左侧 模型列表按次数由高到低排序，柱状图下方模型列表按金额由高到低排序

**应用场景**
![image](https://github.com/Calcium-Ion/new-api/assets/126902077/f1105117-80fd-4b1e-8994-95f016d61f94)

此优化更符合用户习惯，将碾压OpenAI图表，极致提升用户体验。

**Comment by goodstudy12** [comment]
还有就是能不能单纯的看今天一天的数据。现在的时间范围是昨天的这个时间到今天的这个时间，好麻烦

**Comment by Calcium-Ion** [comment]
> 还有就是能不能单纯的看今天一天的数据。现在的时间范围是昨天的这个时间到今天的这个时间，好麻烦

不能，建议自己改代码
