### ISSUE TITLE
渠道响应400状态码时没有重试

### ISSUE THREAD

**Issue by gchuyun** [Calcium-Ion/new-api#193]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
多个不同类型的渠道，后面模型的安全检测不会完全一样。（比如GitHub copilot，它对非编码的问答会返回400状态码）

**预期结果**
希望在收到400状态码后，能在不同类型的渠道重试。比如OpenAI、文心一言、每个自定义类型等。

**Comment by wobure123** [comment]
这个有解决法子吗？感觉目前重试逻辑单一不可控，400,429，非200都可以设置更换渠道重试，就方便了。

**Comment by Calcium-Ion** [comment]
使用渠道状态码复写功能
