### ISSUE TITLE
希望能加入cohere公司command-r等模型的支持

### ISSUE THREAD

**Issue by magicdmer** [Calcium-Ion/new-api#195]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望加入cohere公司command-r模型的支持，可以官方免费申请试用的apikey进行测试

**应用场景**
这个模型角色扮演有一手，而且没有和谐太多

**Comment by miaotouy** [comment]
+1
我本来自己用GPT整了个脚本做中转，但是部署起来各种问题，还是期待添加支持就不用这么麻烦了，直接渠道里key和模型一填就好了

**Comment by magicdmer** [comment]
可以暂时通过：https://github.com/missuo/cohere2openai 这个工程来就集成到newapi

**Comment by magicdmer** [comment]
看了一下，源码这个单词写错了，可以修正一下
var ChannelName = "choere"
