### ISSUE TITLE
可否能增加渠道模型批量导入和批量导出（复制）的功能

### ISSUE THREAD

**Issue by conan-2** [Calcium-Ion/new-api#207]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
添加渠道填写模型时，支持在自定义名称填入如"aaa,bbb,ccc"格式，自动添加为模型aaa、bbb和ccc。并且在已添加的渠道内，支持将所有模型复制为类似格式。
**应用场景**
方便二次创建相同类型和模型的渠道。现只有“批量创建”功能能实现类似功能，但仅限于同时批量添加。如需“复制”已添加的渠道时，只能手动输入一遍模型，比较繁琐。希望大佬能实现这个功能。

**Comment by iszcz** [comment]
#194 
重开了pr，渠道复制。
当时提完后，自己测试发生了一次崩溃所以关了，但是后续使用没有再复现过，找不到原因了，就当他没问题吧- -||
