### ISSUE TITLE
使用pg数据库导致设置打不开

### ISSUE THREAD

**Issue by KenGrofork** [Calcium-Ion/new-api#21]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用pg数据库导致设置打不开，显示白屏
**复现步骤**
使用pg数据库
**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/126143068/58f56ab2-5671-4c2d-b499-09a494fbec1b)

程序报错 2023/11/30 21:39:30 /build/model/ability.go:19 ERROR: syntax error at or near "group" (SQLSTATE 42601)

**Comment by Calcium-Ion** [comment]
最新提交已修复，可以先自行构建镜像
