### ISSUE TITLE
渠道管理-更新所有渠道余额-不起作用

### ISSUE THREAD

**Issue by iszcz** [Calcium-Ion/new-api#214]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道管理-更新所有渠道余额-不起作用
另外单独更新通道余额，需要手动刷新才会显示
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
更新所有渠道余额你是怎么测试不起作用的，我无法复现
单独更新需要刷新确实是bug
