### ISSUE TITLE
是否可能支持上传文件？

### ISSUE THREAD

**Issue by Payne-Wang** [Calcium-Ion/new-api#215]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

大佬好，如题，目前使用gpt-4-all模型上传文件时，均会报错:
```
{
  "error": {
    "message": "fail to decode image config(webp): riff: missing RIFF chunk header (request id: 20240420193515537885062mNC1362C)",
    "type": "new_api_error",
    "param": "",
    "code": "count_token_messages_failed"
  },
  "endpoint": "https://oai.it****ry.com/v1",
  "provider": "openai"
}
```
是否可以增加上传文件（非图片）的功能，感谢！

**Comment by Calcium-Ion** [comment]
上传文件我这边要怎么计费，没有统一的标准

**Comment by yuanjie-ai** [comment]
> 上传文件我这边要怎么计费，没有统一的标准

按次

**Comment by wang0yue** [comment]
openwebui可以上传pdf给gpt3.5，它应该做了把pdf解析成文本的工作

**Comment by realnoob007** [comment]
解决了吗？.docx文件好像不行

**Comment by Calcium-Ion** [comment]
最新版添加了`GET_MEDIA_TOKEN`环境变量，设置为false就能上传文件了
