### ISSUE TITLE
使用gpt4v模型发送图片，报错

### ISSUE THREAD

**Issue by zsychn** [Calcium-Ion/new-api#218]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
报错内容如下：

  "error": {
    "message": "Panic detected, error: interface conversion: interface {} is dto.MessageImageUrl, not map[string]interface {}. Please submit a issue here: https://github.com/Calcium-Ion/new-api (request id: 20240424123455463912930Ri7hlrAZ) (request id: 2024042404345094056769871020898)",
    "type": "new_api_panic",
    "param": "",
    "code": null
  },

**Comment by Calcium-Ion** [comment]
你的请求体呢？
