### ISSUE TITLE
在问题中如果包含了test就会有报错

### ISSUE THREAD

**Issue by dong152389** [Calcium-Ion/new-api#220]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

在问题中如果包含了test就会有报错

**复现步骤**

```java
(PhantomReference<PhantomReferenceTest>) phantomQueue.remove(); 
```
会返回被gc的对象实例吗？我在lobe和chat next web 中都会有这样的提示

**预期结果**

**相关截图**

![image](https://github.com/Calcium-Ion/new-api/assets/49591362/763a36b9-440b-4066-a8a9-15ed05f47ec9)

如果没有的话，请删除此节。

**Comment by baoqihui** [comment]
去设置里看看敏感词没关

**Comment by dong152389** [comment]
> 去设置里看看敏感词没关

哦哦，看到了，谢谢，是我疏忽了
