### ISSUE TITLE
增加dalle-e的b64_json输出格式支持

### ISSUE THREAD

**Issue by mwnu** [Calcium-Ion/new-api#223]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
openai的图片生成模型（dall-e-3和dall-e-2）api图片返回格式 [response_format](https://platform.openai.com/docs/api-reference/images/create#images-create-response_format) 支持url链接和base64格式。

oneapi已经实现了这个[b64_json](https://github.com/songquanpeng/one-api/blob/1c2654320e5b6268b13b6efca40ce37a523d032b/relay/adaptor/ali/image.go#L149)支持，请求new-api也加上。
**应用场景**
url只是临时的会失效，base64作为图片链接能够一直保存。

**Comment by Calcium-Ion** [comment]
dall-e的response_format是支持的
