### ISSUE TITLE
令牌创建时默认无限额度

### ISSUE THREAD

**Issue by Ruler27** [Calcium-Ion/new-api#227]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
经常有人搞错额度限制，创建的令牌是 $1 的，很快就用完了，但是钱包额度还有很多。

而且一般用户是不需要设置额度限制的，各种模型的官网甚至根本就没有额度限制的功能。

希望能够改成默认无限额度，并且下面【设为无限额度】可以改成【设为钱包额度】，更容易理解。

**应用场景**
新用户令牌创建不容易造成理解错误。

**Comment by AthanaD** [comment]
支持，这个令牌默认就应该无限额度，因为这个额度完全没有用，真正是靠钱包的钱消耗
