### ISSUE TITLE
通过管理面板编辑用户导致用户密码丢失

### ISSUE THREAD

**Issue by mwnu** [Calcium-Ion/new-api#230]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
管理员在管理面板——用户管理——编辑用户提交之后，即便没有修改用户的密码，但是旧密码无法登录，新密码未知，只能通过邮件重置。
另外，如果通过API编辑用户而没有传递额度参数（quota），则用户剩余额度会被重置为0.

这两个问题都是版本[v0.2.2.0](https://github.com/users/Calcium-Ion/packages/container/new-api/205443711?tag=v0.2.2.0)之后才出现的，之前没有。
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by 13531446481** [comment]
我也遇到了

**Comment by QSXDY** [comment]
我也遇到了

**Comment by dong152389** [comment]
+1，复现步骤是，我想把用户的组调整一下，然后发现用户的密码也被重置为空了。

**Comment by QSXDY** [comment]
我那天手贱，把root也换了分组，然后你懂的。。。。。。最后去数据库复制了我另一个号的密码到root密码，然后登录root重新改的密码。差点就得重新建个小号来复制密码了~

**Comment by Calcium-Ion** [comment]
请更新到v0.2.2.0-alpha.20或以上版本
