### ISSUE TITLE
怎么从one-api迁移到new-api

### ISSUE THREAD

**Issue by Ward-zzZ** [Calcium-Ion/new-api#231]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我想从one-api迁移到new-api，怎么保留数据，我使用one-api.db启动容器会报错
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by byhooi** [comment]
今天早上遇到同样的问题

> [0.015ms] [rows:0] INSERT INTO `tokens__temp`() SELECT  FROM `tokens`
> [FATAL] 2024/05/06 - 11:56:38 | [failed to initialize database: near ")": syntax error] 
> [SYS] 2024/05/06 - 11:56:39 | New API v0.2.2.0-alpha.19 started 
> [SYS] 2024/05/06 - 11:56:39 | SQL_DSN not set, using SQLite as database 
> [SYS] 2024/05/06 - 11:56:39 | database migration started 
> [FATAL] 2024/05/06 - 11:56:39 | [failed to initialize database: near ")": syntax error]

**Comment by wxy545812093** [comment]
实在不行就上最原始的方法， 手动同步 俩份 sqlite db

**Comment by wang-zhix** [comment]
[SYS] 2024/05/16 - 12:09:48 | New API v0.2.2.0-alpha.27 started
[SYS] 2024/05/16 - 12:09:48 | SQL_DSN not set, using SQLite as database
[SYS] 2024/05/16 - 12:09:48 | database migration started
[FATAL] 2024/05/16 - 12:09:48 | [failed to initialize database: near ")": syntax error]

2024/05/16 12:09:48  near ")": syntax error
[0.008ms] [rows:0] INSERT INTO `tokens__temp`() SELECT  FROM `tokens`


一致的错误

**Comment by maxduke** [comment]
用了最新版好像还是报同样错

```
2024/05/18 16:42:44  near ")": syntax error
new-api    | [0.009ms] [rows:0] INSERT INTO `tokens__temp`() SELECT  FROM `tokens`
new-api    | [FATAL] 2024/05/18 - 16:42:44 | [failed to initialize database: near ")": syntax error] 
new-api    | [SYS] 2024/05/18 - 16:42:51 | New API v0.2.2.1 started 
new-api    | [SYS] 2024/05/18 - 16:42:51 | SQL_DSN not set, using SQLite as database 
new-api    | [SYS] 2024/05/18 - 16:42:51 | database migration started
```

**Comment by Calcium-Ion** [comment]
手动迁移吧

**Comment by maxduke** [comment]
> 手动迁移吧

嗯，只能这样啦，多谢

**Comment by DR-lin-eng** [comment]
我直接复制黏贴过去然后重启容器就解决了

**Comment by Calcium-Ion** [comment]
建议用数据库软件手动迁移
