### ISSUE TITLE
自定义模型加入后不生效

### ISSUE THREAD

**Issue by Linon419** [Calcium-Ion/new-api#235]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [x  ] 我已确认我已升级到最新版本
+ [x  ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
加入自定义模型后，v1/models 没有显示相应模型
**复现步骤**
加入自定义模型，我加入的是gpt-4-turbo-2024-04-09

**相关截图**
<img width="1107" alt="Screen Shot 2024-05-08 at 20 25 35" src="https://github.com/Calcium-Ion/new-api/assets/29937602/57ffa606-aa77-4e4f-9919-015d59deb6ab">
返回结果：
{
    "data": [
        {
            "id": "claude-3-opus-20240229",
            "object": "model",
            "created": 1626777600,
            "owned_by": "aws",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "claude-3-opus-20240229",
            "parent": null
        },
        {
            "id": "dall-e-3",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "dall-e-3",
            "parent": null
        },
        {
            "id": "gpt-3.5-turbo",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-3.5-turbo",
            "parent": null
        },
        {
            "id": "gpt-4",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4",
            "parent": null
        },
        {
            "id": "gpt-4-0125-preview",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4-0125-preview",
            "parent": null
        },
        {
            "id": "gpt-4-1106-preview",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4-1106-preview",
            "parent": null
        },
        {
            "id": "gpt-4-32k-0613",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4-32k-0613",
            "parent": null
        },
        {
            "id": "gpt-4-turbo-preview",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4-turbo-preview",
            "parent": null
        },
        {
            "id": "gpt-4-vision-preview",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "gpt-4-vision-preview",
            "parent": null
        },
        {
            "id": "text-embedding-3-large",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "text-embedding-3-large",
            "parent": null
        },
        {
            "id": "text-embedding-3-small",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "text-embedding-3-small",
            "parent": null
        },
        {
            "id": "text-embedding-ada-002",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "text-embedding-ada-002",
            "parent": null
        },
        {
            "id": "tts-1",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "tts-1",
            "parent": null
        },
        {
            "id": "tts-1-1106",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "tts-1-1106",
            "parent": null
        },
        {
            "id": "tts-1-hd",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "tts-1-hd",
            "parent": null
        },
        {
            "id": "tts-1-hd-1106",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "tts-1-hd-1106",
            "parent": null
        },
        {
            "id": "whisper-1",
            "object": "model",
            "created": 1626777600,
            "owned_by": "openai",
            "permission": [
                {
                    "id": "modelperm-LwHkVFn8AcMItP432fKKDIKJ",
                    "object": "model_permission",
                    "created": 1626777600,
                    "allow_create_engine": true,
                    "allow_sampling": true,
                    "allow_logprobs": true,
                    "allow_search_indices": false,
                    "allow_view": true,
                    "allow_fine_tuning": false,
                    "organization": "*",
                    "group": null,
                    "is_blocking": false
                }
            ],
            "root": "whisper-1",
            "parent": null
        }
    ],
    "object": "list"
}

**Comment by RedwindA** [comment]
同样有该问题，模型可以在chat/completion中被正常请求，但是v1/models的列表中没有该模型

**Comment by 1PercentSync** [comment]
我也遇到了这个问题
