### ISSUE TITLE
无法适配 glm-4

### ISSUE THREAD

**Issue by kenneth-bro** [Calcium-Ion/new-api#236]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
代理设置 https://open.bigmodel.cn/api/paas/v4 后无法访问，判断应该是 请求的 /v1/chat/completion 中的/v1写死导致的。
详细见官方文档: https://open.bigmodel.cn/dev/api#glm-4
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
不需要填写代理地址
