### ISSUE TITLE
渠道余额不能正常显示

### ISSUE THREAD

**Issue by HunterWangwei** [Calcium-Ion/new-api#24]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道余额不能正常显示，
从控制台看点击更新之后是有正常余额返回的，
但是余额那里还是显示0
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/56406873/19c2871c-978e-4064-b4dc-bfafb09a5cbc)

**Comment by Calcium-Ion** [comment]
最新提交已经修复
