### ISSUE TITLE
重定向无法正常使用

### ISSUE THREAD

**Issue by YangguangZhou** [Calcium-Ion/new-api#241]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

New Api中重定向功能无法正常使用

**复现步骤**

使用
```json
{
  "gpt-4-all": "gpt-4"
}
```
进行重定向

**预期结果**

当请求gpt-4-all时，应该重定向到请求gpt-4-模型

**错误结果**
当请求gpt-4时，返回结果正常，但是请求gpt-4-all时会返回错误：status code 503: 当前分组 default 下对于模型 gpt-4-all 无可用渠道 (request id: 2024051210391371373380583132447)

**Comment by Calcium-Ion** [comment]
必须同时添加gpt-4-all和gpt-4两个模型才能重定向

**Comment by YangguangZhou** [comment]
> 必须同时添加gpt-4-all和gpt-4两个模型才能重定向

都有的 但是依然不生效

![Screenshot_20240512-184441.png](https://cdn.jerryz.com.cn/gh/YangguangZhou/image@main/blog/24/5/Screenshot_20240512-184441.png)

**Comment by Calcium-Ion** [comment]
我这边最新版自测是没问题的，你是不是模型多打了空格什么的

**Comment by YangguangZhou** [comment]
> 我这边最新版自测是没问题的，你是不是模型多打了空格什么的

更新到最新版了，也检查了空格还是不行，能加个联系方式您帮我看看吗
