### ISSUE TITLE
渠道限速

### ISSUE THREAD

**Issue by TerrySiu98** [Calcium-Ion/new-api#244]
自定义限速周期和次数来应对不同渠道

**Comment by TerrySiu98** [comment]
自定义限速周期和次数来应对不同渠道

**Comment by TimchaStudio** [comment]
其实用户组限速是最优方案。不同用户，速率不一样。

**Comment by faithererer** [comment]
> 其实用户组限速是最优方案。不同用户，速率不一样。

可是也存在同一用户组不同模型rpm不同的需求呀
