### ISSUE TITLE
Midjourney Proxy时，前端接入缺少参数支持

### ISSUE THREAD

**Issue by wxy545812093** [Calcium-Ion/new-api#249]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
 new-api管理端添加(Midjourney Proxy 或 Midjourney Proxy plus)渠道时，没有填写url的地方。docker镜像已经是拉取最新的了。
**复现步骤**

**预期结果**

**相关截图**
![2024-05-14_195156](https://github.com/Calcium-Ion/new-api/assets/4502958/3eed68e5-cff3-4028-934b-ddc7cc5df3f3)
![2024-05-14_195257](https://github.com/Calcium-Ion/new-api/assets/4502958/1f761831-e160-45a0-bbb6-1942ff34e681)

如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
代理就是填地址的地方
