### ISSUE TITLE
无法复制到剪贴板

### ISSUE THREAD

**Issue by lanyuer** [Calcium-Ion/new-api#250]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在日志页点击模型或者其他地方，弹出“无法复制到剪贴板”

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/5697909/13c4428c-15dd-44bb-ab0a-7fee49538d22)

如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
复制功能必须使用https
