### ISSUE TITLE
telegram 绑定账号时出现：{"message":"无效的请求","success":false}

### ISSUE THREAD

**Issue by pppfz** [Calcium-Ion/new-api#264]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题
**复现步骤**
开启telegram登录

![image](https://github.com/Calcium-Ion/new-api/assets/119300926/ff5d9115-dc6b-48cb-872f-3e9d6ba1e8cc)

![image](https://github.com/Calcium-Ion/new-api/assets/119300926/c0ed9f89-135b-4663-b27b-1387c4c0082b)

**预期结果**
成功绑定telegram账号

**Comment by sam13142023** [comment]
同求，也遇到了同样的问题
注册的时候使用telegram也会提示错误的请求
