### ISSUE TITLE
模型价格页面分组倍率显示错误

### ISSUE THREAD

**Issue by ChangeYu0229** [Calcium-Ion/new-api#275]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
模型价格页面分组倍率显示错误，后台修改为0.95，实际还是显示1
**复现步骤**
直接打开模型价格页面
**预期结果**
希望同步分组倍率显示
**相关截图**
![a497847b3c9581bf278814ecc972d94c](https://github.com/Calcium-Ion/new-api/assets/42216064/887e8921-3db2-4a43-bcb8-43c9c2560c1f)

**Comment by LuckyWang6** [comment]
同样问题！
