### ISSUE TITLE
刷新log时候不定期出现空白页面

### ISSUE THREAD

**Issue by ChangeYu0229** [Calcium-Ion/new-api#276]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
刷新log时候不定期出现空白页面
**复现步骤**
打开log后选择充值
**预期结果**
正常
**相关截图**
<img width="557" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/42216064/aea43721-4402-419b-a95d-d534d96ded89">

**Comment by DC925928496** [comment]
+1，同样的问题

**Comment by chawaa** [comment]
+1，购买支付成功之后跳空白页，控制台报错一致。

**Comment by Calcium-Ion** [comment]
最新版已解决
