### ISSUE TITLE
新增对字节跳动 doubao 的支持

### ISSUE THREAD

**Issue by QSXDY** [Calcium-Ion/new-api#279]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
新增对字节跳动 doubao 的支持
**应用场景**
新增对字节跳动 doubao 的支持

**Comment by wang0yue** [comment]
解决方案：参考https://blog.ccrui.cn/archives/dou-bao-da-mo-xing-zhuan-huan-wei-openai-jie-kou.html
如果要在newapi中使用，选择自定义渠道，baseurl填写https://ark.cn-beijing.volces.com/api/v3/chat/completions
其他的参考上面的 blog即可

**Comment by kenneth-bro** [comment]
> 解决方案：参考https://blog.ccrui.cn/archives/dou-bao-da-mo-xing-zhuan-huan-wei-openai-jie-kou.html 如果要在newapi中使用，选择自定义渠道，baseurl填写https://ark.cn-beijing.volces.com/api/v3/chat/completions 其他的参考上面的 blog即可

设置了这个baseurl 404

**Comment by kangyiwen** [comment]
https://ark.cn-beijing.volces.com/api/v3/chat/completions/     

要最后带 / 就可以用了，不会 404
