### ISSUE TITLE
增加类似【聊天】页面的自定义页面

### ISSUE THREAD

**Issue by Ruler27** [Calcium-Ion/new-api#280]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
增加一个或多个自定义页面，类似于【聊天】页面那样，嵌入一个网页，可以是文档、详细教程之类的。

**应用场景**
把需要详细说明的内容直接添加链接就能引用过来，同时又不需要在New-API里面进行内容编辑

**Comment by QSXDY** [comment]
那个关于页面不是可以利用起来吗？

**Comment by Zeta-ZhaoLi** [comment]
> 那个关于页面不是可以利用起来吗？

能直接引用链接的话编辑内容方便些，可以直接把博客或者文档之类的插进来

**Comment by hcppxgit** [comment]
关于和首页可以直接填写链接，你怎么不先试试
