### ISSUE TITLE
希望能添加限制渠道专门使用流式和非流式返回，有些逆向项目只支持流式或者只支持非流式，希望能添加限制

### ISSUE THREAD

**Issue by DR-lin-eng** [Calcium-Ion/new-api#284]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ 我已确认目前没有类似 issue
+ 我已确认我已升级到最新版本
+ 我已完整查看过项目 README，已确定现有版本无法满足需求
+ 理解并愿意跟进此 issue，协助测试和提供反馈
+ 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
如题
**应用场景**
如题
请求大佬添加，谢谢

**Comment by Calcium-Ion** [comment]
不会添加这个功能

**Comment by rinch-wu** [comment]
@Calcium-Ion 
建议重新考虑下，最近用iflow总是被截断，很难受，vibecoding的时候其实不在意是不是前几个字有多快，一次输出完才是最高效的。希望能有一个按钮，开启后不管收到的请求是不是流式的，都使用非流式请求上游api
