### ISSUE TITLE
system_fingerprint字段影响解析

### ISSUE THREAD

**Issue by kenneth-bro** [Calcium-Ion/new-api#285]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [x  ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x  ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

system_fingerprint 这个字段是 new-api增加的吗？这个字段会影响使用哎。而且这个字段的位置还在随时变。

**复现步骤**

**预期结果**

**相关截图**
![280421e1f344c37f2d3d49186b06883f](https://github.com/Calcium-Ion/new-api/assets/19256972/4c5c8382-0d2d-43df-ad47-a5f8989cfcdf)

![5bd2caeeb2bfb4cd00789d7578d1dfe9](https://github.com/Calcium-Ion/new-api/assets/19256972/55c1889d-5820-4fd0-bd2d-d56d8770b540)

**Comment by Calcium-Ion** [comment]
这是OpenAI的标准格式里就有的
