### ISSUE TITLE
调用文心一言报错

### ISSUE THREAD

**Issue by wang-zhix** [Calcium-Ion/new-api#289]
1.添加完渠道后使用 自带的测试 不会报错
![image](https://github.com/Calcium-Ion/new-api/assets/59219784/aace58f9-38ec-4d9a-a61a-27d6641ef68c)
2.使用chatbox会出现不返回结果的问题 日志如下
![image](https://github.com/Calcium-Ion/new-api/assets/59219784/c9cefeea-2f3a-4da5-aac2-4fdc5ca15538)
3.使用沉浸式翻译报错日志如下
![image](https://github.com/Calcium-Ion/new-api/assets/59219784/2bf5a16b-8632-4f03-9a74-8ae7879a0acd)

**Comment by wang-zhix** [comment]
使用Docker    版本：v0.2.4.0-alpha.2

**Comment by jimmyshjj** [comment]
问题应该是在message中传递了system prompt，看下issue #277

**Comment by wang-zhix** [comment]
one-api 是正常的，  我暂时先使用one-api吧

**Comment by Calcium-Ion** [comment]
已修复
