### ISSUE TITLE
大佬，你把个人信息更新功能忘记了！无法自主修改密码。

### ISSUE THREAD

**Issue by guoruqiang** [Calcium-Ion/new-api#29]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用户忘记密码，只能密码重置，重置了进去后无法修改！
**复现步骤**
重置密码就是如此
**预期结果**
希望保留原one-api可以在更新用户信息的地方修改自己的密码。
**相关截图**
![屏幕截图 2023-12-12 215033](https://github.com/Calcium-Ion/new-api/assets/61670021/346f1fc5-f1a3-4e10-9e64-aab72cd85c10)

**Comment by guoruqiang** [comment]
不能修改重置密码，那就保留一下那个个人信息更新吧！

**Comment by guoruqiang** [comment]
大佬别忘了哈

**Comment by Calcium-Ion** [comment]
最新commit已修复
