### ISSUE TITLE
在openwrt上运行的问题

### ISSUE THREAD

**Issue by liaoke01** [Calcium-Ion/new-api#290]
我已升级至最新版，并且看了相关的readme,没有我遇到的问题,我在openwrt安装docker,然后运行部署命令，并且将数据库换成我自己的，在设置端口转发从外部互联网可以通过300端口访问到网站，但是在各大chatgpt聊天网站里调用api接口的时候会一直转圈，没有响应

**Comment by iliaoke** [comment]
接口名字后面我带有:3000
