### ISSUE TITLE
聊天上能否适配 chatgpt-web-midjourney-proxy

### ISSUE THREAD

**Issue by Dooy** [Calcium-Ion/new-api#293]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
https://github.com/Dooy/chatgpt-web-midjourney-proxy
特别适配 new-api 因为 chatgpt-web-midjourney-proxy 也是在支持对话模型的基础上加上了 `midjourney-proxy`的前端

同时 `midjourney-proxy` `midjourney-proxy-plus` 项目都有推荐 希望大佬能在聊天模块支持上 `chatgpt-web-midjourney-proxy`

<img width="723" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/3765401/60f327f3-fecd-40f4-af17-96f1dbecbe72">

**应用场景**
聊天模块 在支持对话模型上支持 `midjourney-proxy`的前端

**Comment by Calcium-Ion** [comment]
已经适配了啊。令牌聊天选项第二个不就是吗

**Comment by Dooy** [comment]
谢谢 大佬
