### ISSUE TITLE
在渠道页面根据分组筛选渠道后，测试按钮的模型下拉菜单无法弹出

### ISSUE THREAD

**Issue by RedwindA** [Calcium-Ion/new-api#302]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [√] 我已确认目前没有类似 issue
+ [√]我已确认我已升级到最新版本
+ [√]] 我已完整查看过项目 README，尤其是常见问题部分
+ [√] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [√]] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题
**复现步骤**
如题，在此处筛选渠道
![image](https://github.com/Calcium-Ion/new-api/assets/128586631/bdce5012-f51a-47b5-adfa-b24bd33c6800)
**预期结果**
测试模型列表正确弹出

**Comment by zhanghao123321** [comment]
我在加一个：设置的超时5s，测试所有渠道后，并没有自动禁止渠道，如下图：
![image](https://github.com/Calcium-Ion/new-api/assets/65217421/f2074776-665e-400f-a438-f7bc6e6206f6)

**Comment by RedwindA** [comment]
> 我在加一个：设置的超时5s，测试所有渠道后，并没有自动禁止渠道，如下图

不同的issue请新建一个，不要在别的issue下提不相关的issue
