### ISSUE TITLE
腾讯混元填写hunyuan-lite，但实际调用的确是hunyuan-pro

### ISSUE THREAD

**Issue by luomo-pro** [Calcium-Ion/new-api#303]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
之前腾讯混元的hunyuan-lite说免费开放了，我就填写了自定义模型名称hunyuan-lite。
但今天一看账单，发现还是产生了调用费用，于是去腾讯的控制台里查看，发现调用日志都是hunyuan-pro的，而lite那都是显示没有调用。
newapi这边的日志显示调用的事hunyuan-lite，感觉是实际调用的时出现了问题。
**复现步骤**
创建一个腾讯混元渠道，添加自定义模型 hunyuan-lite
**预期结果**
应该调用hunyuan-lite

**Comment by QSXDY** [comment]
我也遇见了，应该是6月6号腾讯更新了接口，中转这边没更新造成的
![QQ图片20240610121414](https://github.com/Calcium-Ion/new-api/assets/109550764/cc0c0785-7970-4df0-94c2-d745ea6b7e45)
![QQ图片20240610121419](https://github.com/Calcium-Ion/new-api/assets/109550764/f300985c-f20b-490e-a3e4-a3a8769096de)
