### ISSUE TITLE
添加聊天链接后在new-api中聊天设置好api地址和key关闭new-api下次打开丢失配置

### ISSUE THREAD

**Issue by pizixi** [Calcium-Ion/new-api#31]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
> * [x] 我已确认目前没有类似 issue
> * [x] 我已确认我已升级到最新版本
> * [x] 我已完整查看过项目 README，尤其是常见问题部分
> * [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
> * [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
关闭new-api网页，重新打开，之前配置的聊天的自定义url和key丢失
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
请设置数据库连接地址或者映射容器/data路径，new-api没有这个问题
