### ISSUE TITLE
fastgpt渠道能否增加一个"chatId": "111"的参数

### ISSUE THREAD

**Issue by Mgrsc** [Calcium-Ion/new-api#315]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
chatId: string | undefined 。
为 undefined 时（不传入），不使用 FastGpt 提供的上下文功能，完全通过传入的 messages 构建上下文。 不会将你的记录存储到数据库中，你也无法在记录汇总中查阅到。
为非空字符串时，意味着使用 chatId 进行对话，自动从 FastGpt 数据库取历史记录，并使用 messages 数组最后一个内容作为用户问题。请自行确保 chatId 唯一，长度小于250，通常可以是自己系统的对话框ID。

当不传入chatid时候fastgpt看不到api日志，所以有时候需要chatid配置

**Comment by xmu714** [comment]
你好，请问这个功能在哪个版本加上了吗，我用的v0.2.7.5依然没有传

**Comment by xiaotianwnag** [comment]
顶一下，希望能够增加chatid参数
