### ISSUE TITLE
测试所有渠道报错panic

### ISSUE THREAD

**Issue by zhanghao123321** [Calcium-Ion/new-api#319]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，尤其是常见问题部分
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
测试所有渠道报错panic
**复现步骤**
点击测试所有渠道，刷新页面，会直接返回到登录页
**预期结果**

**相关截图**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda0da2]

goroutine 116 [running]:
one-api/controller.testAllChannels.func1()
	/build/controller/channel-test.go:224 +0x3e2
created by one-api/controller.testAllChannels in goroutine 53
	/build/controller/channel-test.go:201 +0x1c5

**Comment by fevrax** [comment]
我也遇到了，报错和你的一样。你是怎么解决的呢？
