### ISSUE TITLE
无法像one-api一样指定渠道id

### ISSUE THREAD

**Issue by mouxangithub** [Calcium-Ion/new-api#32]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请求api的时候，Authorization的key是可以Authorization: Bearer ONE_API_KEY-CHANNEL_ID携带渠道id进行请求，但我这边测试似乎不行
**复现步骤**

**预期结果**

**相关截图**
![I3S3IZQGE`K$ GFT YG1{%O](https://github.com/Calcium-Ion/new-api/assets/48978046/091e9648-dad8-44c5-a74b-f102df5dd102)
![}B8J${RGXT PF2L5LDHB)EA](https://github.com/Calcium-Ion/new-api/assets/48978046/055c9658-a9be-4d57-8315-5a9fc3efd1db)

**Comment by Calcium-Ion** [comment]
最新提交已修复

**Comment by aiken** [comment]
## 补充调研结果 —— 根因完全定位

### 2025-05-10 更新

**1. 模型调用值大小写问题（已确认）**

直接 curl 测试京东 MaaS API：

| model 字段 | 结果 |
|-----------|------|
| `kimi-k2.5` | ❌ 404：`model kimi-k2.5, app 'app-1n5f9i3up3' not found` |
| `Kimi-K2.5` | ✅ 200：正常返回 choices |

京东 MaaS 文档 https://docs.jdcloud.com/cn/jdaip/thinking 中明确使用 `"model": "Kimi-K2.5"`（首字母 K 大写）。

**2. 模型映射配置位置（重要纠正）**

模型名映射**不是在「模型管理」中配置，而是在「渠道管理」中配置**。

代码路径：`relay/helper/model_mapped.go:29-66`

- 每个渠道有 `model_mapping` 字段（JSON）
- 格式：`{"用户请求模型名": "上游实际模型名"}`
- 支持链式映射和循环检测

**3. 正确的修复步骤（无需改代码）**

进入后台「渠道管理」→ 编辑配置了 `kimi-k2.5` 的京东渠道 → 在 **模型映射** 字段填入：

```json
{"kimi-k2.5": "Kimi-K2.5"}
```

保存后，该渠道收到 `kimi-k2.5` 请求时，会自动将 model 字段替换为 `Kimi-K2.5` 再转发给京东 MaaS。

---

### 其他京东 MaaS 模型调用值（参考）

来自 https://docs.jdcloud.com/cn/jdaip/thinking：

- `Kimi-K2.5`
- `Kimi-K2-Turbo`
- `DeepSeek-V3.2`
- `GLM-5`
- `GLM-4.7`
- `MiniMax-M2.5`
- `Qwen3-Coder`

如需接入这些模型，同样在对应渠道的 `model_mapping` 中配置大小写映射即可。

**Comment by aiken** [comment]
✅ **已解决**

通过在渠道管理的 **模型映射** 中配置 ，kimi-k2.5 现已可正常通过京东 MaaS 渠道使用。
