### ISSUE TITLE
部署时遇到问题，重启无效

### ISSUE THREAD

**Issue by 123ziqiqinfeng** [Calcium-Ion/new-api#329]
[**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
部署时遇到问题，重启无效
**复现步骤**
无
**预期结果**
无
**相关截图**
![FFDE402D894EED6ECE96CC6063CC5676](https://github.com/Calcium-Ion/new-api/assets/140558012/bc346f1c-0cb4-4350-8ca7-b434123d49c8)

**Comment by 123ziqiqinfeng** [comment]
可以加我qq2551516722联系我，还可以发我邮箱xiangqicuang0608@outlook.com\xiangqicuangappgf@outlook.com\2551516722@qq.com

**Comment by KamiPasi** [comment]
你把报错信息给gpt看看
