### ISSUE TITLE
建议可以添加swap_face人物换脸功能

### ISSUE THREAD

**Issue by think007** [Calcium-Ion/new-api#34]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by think007** [comment]
建议可以添加swap_face人物换脸功能

**Comment by Calcium-Ion** [comment]
能提供一下地址吗？没听说过这个api

**Comment by think007** [comment]
https://github.com/deepinsight/insightface
参考：https://zhuanlan.zhihu.com/p/628212649?utm_id=0&amp;wd=&amp;eqid=9653f7d9004a9785000000056496db37

**Comment by think007** [comment]
重复了
