### ISSUE TITLE
api.smnet.asia base url 多少

### ISSUE THREAD

**Issue by onlyhuman028** [Calcium-Ion/new-api#341]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
key只能在官网用，导入原生chat-next-web

**复现步骤**
baseurl设置为 https://api.smnet.asia/，https://api.smnet.asia/v1都不能使用
**预期结果**
可以非官网使用apikey

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/90880928/a26e361c-ebf7-4ec3-84ac-2a75b6ee7458)

**Comment by blackh1** [comment]
你这个应该填smnet那边的key；顺便提一下，这个不是newapi的问题吧
