### ISSUE TITLE
请求增加邮箱登录

### ISSUE THREAD

**Issue by Yan-Zero** [Calcium-Ion/new-api#343]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

一般而言，同一个邮箱不能绑定多个用户，那么邮箱其实具备唯一性，那么为什么不能添加一个邮箱登录的功能呢？

**应用场景**

方便用户登录

**Comment by iszcz** [comment]
model.user 301行代码更换成
err = DB.Where("username = ?", user.Username).First(user).Error
if err != nil {
err := DB.Where("email = ?", user.Username).First(user).Error
if err != nil {
	return errors.New("用户名或密码错误，或用户已被封禁")
}
}
	就可以了
