### ISSUE TITLE
希望增加一个参数stream_options，用来获取上游正确的token数量

### ISSUE THREAD

**Issue by yyhhyyyyyy** [Calcium-Ion/new-api#345]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
由于claude等token计算方式与openai的计算方式不同，第一层new-api直接对接的claude，那么可以返回正确的token给第一层的new-api;但是如果第二层new-api对接的是第一层的new-api，那么将无法获取到正确的token数量，而是直接使用openai的token计算方式来计算的token，这样的token是有问题的，因此希望增加一个 stream_options 参数 获取上游正确的token数量

具体可以参考 https://github.com/MartialBE/one-api  这个项目中的 `stream_options StreamOptions`

**Comment by Calcium-Ion** [comment]
已初步支持
