### ISSUE TITLE
 易支付  配置 支付地址 和 回调地址 为 https://ezfp.cn/mapi.php ，发现付款成功后用户余额不变

### ISSUE THREAD

**Issue by tomridder** [Calcium-Ion/new-api#346]
易支付  配置 支付地址 和 回调地址 为 https://ezfp.cn/mapi.php ，发现付款成功后用户余额不变
用的不是扫码支付，是登录支付宝账户支付

正确的配置方式应该怎么样呢，谢谢

**Comment by Zuo-Cheng** [comment]
解决了吗？
