### ISSUE TITLE
日志-详情 中计算的扣费和实际扣费不一致！

### ISSUE THREAD

**Issue by piwawa** [Calcium-Ion/new-api#351]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gpt-3.5-turbo，模型倍率 0.25，分组倍率 2.50，补全倍率 3.00，计算过程令人困惑！模型倍率已重置为默认，没有做任何修改。

**预期结果**
计算结果应该与实际扣费一致，且计算过程中明确注明各个参数对应的倍率。

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/46926496/45dc5dc8-46e5-44ca-88a1-2573a8b44baa)
![image](https://github.com/Calcium-Ion/new-api/assets/46926496/2b2edede-0306-4e27-9fbd-adcd9cf74d3b)
![image](https://github.com/Calcium-Ion/new-api/assets/46926496/ffa1b934-bfc7-4a08-ac4d-23095e1b6bff)

**Comment by piwawa** [comment]
@Calcium-Ion  How can you close it as **completed** without any solution or explanation?

**Comment by Calcium-Ion** [comment]
我是你保姆吗怎么解决的还要和你报告？

**Comment by Calcium-Ion** [comment]
不能自己看一下commit记录吗
