### ISSUE TITLE
添加渠道功能选择选项（FC和识图）以优化渠道调用

### ISSUE THREAD

**Issue by slot181** [Calcium-Ion/new-api#352]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

请求添加渠道功能选择选项。具体来说：

1. 为每个渠道设置添加两个可选功能：
   - FC功能（Function Calling）
   - 识图功能

2. 在渠道设置中，允许管理员开启或关闭这些功能。

3. 根据用户的请求内容，智能选择合适的渠道：
   - 如果用户请求包含识图需求，只调用开启了识图功能的渠道。
   - 如果用户请求需要使用FC功能，只调用开启了FC功能的渠道。
   - 如果某个渠道同时开启了两个功能，它应该也可以被列入前两者可调用的渠道列表。

**应用场景**

1. 资源优化：通过精确控制每个渠道的功能，可以更有效地分配计算资源，避免不必要的API调用。

2. 管理员体验提升：管理员无需再考虑某些渠道无法使用某些功能而考虑怎么调动优先度，系统会自动根据需求选择最合适的渠道。

3. 灵活的系统配置：管理员可以根据实际需求和资源情况，灵活地开启或关闭各个渠道的特定功能。

**Comment by Calcium-Ion** [comment]
这类功能属于个人需求，不会考虑添加
