### ISSUE TITLE
希望能设置首字超时时间

### ISSUE THREAD

**Issue by Feliks151450** [Calcium-Ion/new-api#357]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望能设置首字超时时间（比如10秒），10秒内没有接受到第一个token就直接报错并触发重试
**应用场景**
目前在日志已经能看到首字时间了，有些场景下上游可能故障导致一直没有回复，自然也不会有重试，最后变成了空回复，影响用户体验。支持首字超时可以及时在上游无响应时切换到其他渠道回复

**Comment by Calcium-Ion** [comment]
环境变量STREAMING_TIMEOUT可以达到限制首字时间的效果，超时会在日志中显示为空补，new api不会出超时重试的功能

**Comment by Feliks151450** [comment]
> 环境变量STREAMING_TIMEOUT可以达到限制首字时间的效果，超时会在日志中显示为空补，new api不会出超时重试的功能

你好，似乎这个环境变量没有起到限制首字时间的作用，已经已经设置为30，但是50秒了才报错。
<img width="318" alt="image" src="https://github.com/user-attachments/assets/72530fb7-80d3-4c0d-aecb-17ef43bcda42">
另外还有一个bug，输入明显太长的时候也不会报错，已经2620k的输入了没有报错，首字时间超时也没有生效，最后用了70秒才显示空补
<img width="587" alt="image" src="https://github.com/user-attachments/assets/6447aa20-f8f0-419f-9940-863c72db1a11">

**Comment by Calcium-Ion** [comment]
首先需要最新版STREAMING_TIMEOUT才能限制首字，您的版本是多少呢？
其次new api不会限制最大输入，如果你觉得有必要，请提交pr

**Comment by Feliks151450** [comment]
> 首先需要最新版STREAMING_TIMEOUT才能限制首字，您的版本是多少呢？ 其次new api不会限制最大输入，如果你觉得有必要，请提交pr
STREAMING_TIMEOUT=30，版本就是最新的2.7.1

**Comment by Feliks151450** [comment]
> 首先需要最新版STREAMING_TIMEOUT才能限制首字，您的版本是多少呢？ 其次new api不会限制最大输入，如果你觉得有必要，请提交pr

STREAMING_TIMEOUT=30，版本就是最新的2.7.1

**Comment by Calcium-Ion** [comment]
> > 首先需要最新版STREAMING_TIMEOUT才能限制首字，您的版本是多少呢？ 其次new api不会限制最大输入，如果你觉得有必要，请提交pr
> 
> STREAMING_TIMEOUT=30，版本就是最新的2.7.1

目前已经能大概限制超时时间，这个参数会受到客户端影响如果客户端提前断开也会导致卡死请自行调整参数
