### ISSUE TITLE
无法正常显示运营设置

### ISSUE THREAD

**Issue by 2693551060** [Calcium-Ion/new-api#359]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
无法正常显示运营设置
**复现步骤**
安装最新版镜像，点击运营设置
**预期结果**
正常显示运营设置内容
**相关截图**

图片![图片](https://image.chenjianming.fun/file/15cc955c98862d1181137.png)
视频![视频]
(https://image.chenjianming.fun/file/a00b6d85dd0d0cc43d8bc.mp4)
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
换个浏览器
