### ISSUE TITLE
加入智谱清言最新模型 `glm-4-alltools` 的支持

### ISSUE THREAD

**Issue by magicdmer** [Calcium-Ion/new-api#364]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
该模型为智谱清言弄出来的一个多合一的多模态模型，可以通过api调用多模态能力，支持图片，代码，文本，联网。
官方介绍：https://mp.weixin.qq.com/s/ZllgH2Q-qUrr4VsZTdKu0A
官方文档：https://bigmodel.cn/dev/api#glm-4-alltools

**应用场景**
这下子方便了，一个模型搞定所有的场景

**Comment by magicdmer** [comment]
目前添加自定义模型后，测试模型会提示：
`错误：status code 400: 当前模型不支持SYNC调用方式`

**Comment by Calcium-Ion** [comment]
你使用的是什么渠道类型，我看了一下文档，应该是支持的，需要选择 `智谱 GLM-4V`类型

**Comment by magicdmer** [comment]
> 你使用的是什么渠道类型，我看了一下文档，应该是支持的，需要选择 `智谱 GLM-4V`类型

我使用的是GLM-4V，官方渠道，点击glm-4-alltools模型提示 

`错误：status code 400: 当前模型不支持SYNC调用方式`
![20240717113734](https://github.com/user-attachments/assets/efe7ba67-d9c2-4a5e-951c-61d5c04e8e67)

**Comment by xy3xy3** [comment]
> > 你使用的是什么渠道类型，我看了一下文档，应该是支持的，需要选择 `智谱 GLM-4V`类型
> 
> 我使用的是GLM-4V，官方渠道，点击glm-4-alltools模型提示
> 
> `错误：status code 400: 当前模型不支持SYNC调用方式` ![20240717113734](https://private-user-images.githubusercontent.com/5556368/349351653-efe7ba67-d9c2-4a5e-951c-61d5c04e8e67.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDQ0NjYsIm5iZiI6MTcyMTY0NDE2NiwicGF0aCI6Ii81NTU2MzY4LzM0OTM1MTY1My1lZmU3YmE2Ny1kOWMyLTRhNWUtOTUxYy02MWQ1YzA0ZThlNjcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTAyOTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNiOTdiMGFjODcxYzc2ZDExOWVkZDFjZjQ0YjdhZGFkZTAxZTgwMGNlNjUwZWQzZDM5OTY2NTY1ZTZkNmM4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XXDJ__7yfrTGXSx14k8BMHUfLEjduRe985SCY1TJOZ4)

会不会只能stream调用呢？所以你点测试就不行

**Comment by xy3xy3** [comment]
> > 你使用的是什么渠道类型，我看了一下文档，应该是支持的，需要选择 `智谱 GLM-4V`类型
> 
> 我使用的是GLM-4V，官方渠道，点击glm-4-alltools模型提示
> 
> `错误：status code 400: 当前模型不支持SYNC调用方式` ![20240717113734](https://private-user-images.githubusercontent.com/5556368/349351653-efe7ba67-d9c2-4a5e-951c-61d5c04e8e67.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDQ1NDQsIm5iZiI6MTcyMTY0NDI0NCwicGF0aCI6Ii81NTU2MzY4LzM0OTM1MTY1My1lZmU3YmE2Ny1kOWMyLTRhNWUtOTUxYy02MWQ1YzA0ZThlNjcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMTAzMDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU5MzBiMDYxZTk2MTI3Y2MyMTljNzMwZTAxZjQ3ZWFjMGM0OWMwODE4NDNjYTc0ZDJmYjQ3ZjVlMjg2YTBjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1HFKjc6TwdyGDRa3tkc-teCgnSj3DolP_jCRRe2gyoc)

![image](https://github.com/user-attachments/assets/ad4a4e28-ea24-4e74-bf32-4eef1ebdd6c1)
官方文档写了只支持sse

**Comment by yuanjie-ai** [comment]
我这已支持

**Comment by Calcium-Ion** [comment]
是只支持stream调用
