### ISSUE TITLE
自动禁用不生效

### ISSUE THREAD

**Issue by kenneth-bro** [Calcium-Ion/new-api#376]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道已欠费后未自动禁用

**复现步骤**
![image](https://github.com/user-attachments/assets/ce7eeaa6-4995-4e27-8206-334d25b30561)
![image](https://github.com/user-attachments/assets/cc09bed0-33bb-4dad-b5b8-9d062291691d)

**预期结果**
如果访问不正常后就自动禁用

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
自动禁用只适配OpenAI官方格式，你的这个欠费报错状态码是429，明显不规范，自然不会禁用。

**Comment by OreoProMax** [comment]
> 自动禁用只适配OpenAI官方格式，你的这个欠费报错状态码是429，明显不规范，自然不会禁用。

请问哪些状态码可以触发自动禁用呢？只有401么？
