### ISSUE TITLE
能不能麻烦大佬支持一下VertexAI

### ISSUE THREAD

**Issue by ssssssshi** [Calcium-Ion/new-api#377]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
麻烦支持一下VertexAI，这个可以用claude3-5, one-api已经有了

**应用场景**

**Comment by LukcyOne** [comment]
确实,如果能直接支持Vertex那gcp那还能少一段中转,估计挺多人能用上的。希望作者大大可以考虑一下。

**Comment by Calcium-Ion** [comment]
在路上了，不要着急

**Comment by ssssssshi** [comment]
upupup

**Comment by wxy-skye** [comment]
还没有支持

**Comment by QingyeSC** [comment]
up

**Comment by endercatone** [comment]
up

**Comment by Calcium-Ion** [comment]
请提供测试json
