### ISSUE TITLE
tools不兼容

### ISSUE THREAD

**Issue by yuanjie-ai** [Calcium-Ion/new-api#388]
"content": "Error code: 400 - {'error': {'code': '1214', 'message': 'tools[0].function.name:不能为空'}}",

**Comment by yuanjie-ai** [comment]
![image](https://github.com/user-attachments/assets/8ce97af1-7c1b-4b78-b033-c419d0c5b81f)

**Comment by yuanjie-ai** [comment]
```
"tools": [
{
"id": "",
"type": "web_browser",
"function": {
"name": "web_browser",
"parameters": "web_browser"
}
```
newapi里的结构体是错的
最新的sdk
![image](https://github.com/user-attachments/assets/01930b01-a41e-47ce-a939-1761f8766f2c)

**Comment by Calcium-Ion** [comment]
你自己的问题

**Comment by yuanjie-ai** [comment]
拉鸡巴倒吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Calcium-Ion/new-api] tools不兼容 (Issue #388)




 
你自己的问题

**Comment by yuanjie-ai** [comment]
我自己兼容了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月26日(周五) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Calcium-Ion/new-api] tools不兼容 (Issue #388)




 
你自己的问题

**Comment by Calcium-Ion** [comment]
就是你妈的你自己的问题你还在这发神经，有病？
