### ISSUE TITLE
新版本new-api对接其他人的new-api的mj无法正常工作

### ISSUE THREAD

**Issue by guoruqiang** [Calcium-Ion/new-api#39]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我对接了别人利用new-api项目搭建的mj模型，无法正常使用。回退上一个版本0.0.9无此问题。
**复现步骤**
对接别人利用new-api搭建的mj，就会无法出图

**预期结果**

**相关截图**
docker logs
![11111111](https://github.com/Calcium-Ion/new-api/assets/61670021/d278754f-c8f8-4059-8864-c03a268d7663)
对接方的显示出图了
![2222222](https://github.com/Calcium-Ion/new-api/assets/61670021/6bf8f2ba-a152-477e-a95a-da469805e921)
我这边不显示出图
![333333333](https://github.com/Calcium-Ion/new-api/assets/61670021/c30022c0-f257-409b-8d4b-87f174a452c3)
回退版本后，成功出图。
![44444444](https://github.com/Calcium-Ion/new-api/assets/61670021/2fcbe66c-453b-4d69-95d4-9e8bb710a8e5)

**Comment by Calcium-Ion** [comment]
已修复，需要上游同步更新最新版

**Comment by hhtower** [comment]
现在还有这个问题
Get Task parse body error2: json: cannot unmarshal object into Go value of type []controller.Midjourney，返回结果不带任务id
