### ISSUE TITLE
无法使用outlook发送邮件

### ISSUE THREAD

**Issue by ddaodan** [Calcium-Ion/new-api#390]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如果stmp设置为outlook的邮箱，会发送失败
oneapi也存在这个问题，且一直未修复：https://github.com/songquanpeng/one-api/issues/108
**复现步骤**
- 设置-系统设置-配置stmp
- 填写outlook邮箱的stmp信息：
```配置 SMTP
用以支持系统的邮件发送
SMTP 服务器地址
smtp.outlook.com
SMTP 端口
587
SMTP 账户
xxx@outlook.com
SMTP 发送者邮箱
xxx@outlook.com
SMTP 访问凭证

```
- 转到个人设置，在个人信息中绑定邮箱
- 或者直接向api`/api/verification?email=xxx@qq.com&turnstile=`发送请求
**预期结果**
正常发送邮件

**Comment by ddaodan** [comment]
更新了之后测试了一下，还是不行，不过现在会弹出一个提示：
错误：504 5.7.4 Unrecognized authentication type [TYAPR01CA0073.jpnprd01.prod.outlook.com 2024-07-31T20:49:56.170Z 08DCB1590CFAC6B7]
是因为我用的ofb账户的原因吗？

**Comment by OswinWu** [comment]
> 更新了之后测试了一下，还是不行，不过现在会弹出一个提示： 错误：504 5.7.4 Unrecognized authentication type [TYAPR01CA0073.jpnprd01.prod.outlook.com 2024-07-31T20:49:56.170Z 08DCB1590CFAC6B7] 是因为我用的ofb账户的原因吗？

你邮箱的后缀是什么，不是outlook.com对嘛？

**Comment by ddaodan** [comment]
> 你邮箱的后缀是什么，不是outlook.com对嘛？

不是，是@xxx.onmicrosoft.com
onedrive for business 的邮箱

**Comment by OswinWu** [comment]
> > 你邮箱的后缀是什么，不是outlook.com对嘛？
> 
> 不是，是@xxx.onmicrosoft.com onedrive for business 的邮箱

等我改改
