### ISSUE TITLE
管理员日志显示对话详情

### ISSUE THREAD

**Issue by mmwong1984** [Calcium-Ion/new-api#397]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认我已升级到最新版本
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在后台日志上显示对话详情

**Comment by Calcium-Ion** [comment]
new不会添加该功能
