### ISSUE TITLE
渠道测试失败。

### ISSUE THREAD

**Issue by sqiangcao99** [Calcium-Ion/new-api#402]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![image](https://github.com/user-attachments/assets/b7000e4a-f6de-47b3-895e-67e9bcba7c24)

**复现步骤**
在腾讯云vps上部署，使用默认的安装命令启动，
`docker run --name new-api -d --restart always -p 3000:3000 -e TZ=Asia/Shanghai -v /home/ubuntu/data/new-api:/data calciumion/new-api:latest`
添加渠道之后，渠道无法测试通过。已经确定使用sealos部署是可以正常运行的，但是在私有的vps上不行。请问应该如何排查？

**Comment by Calcium-Ion** [comment]
网络问题
