### ISSUE TITLE
gemini-1.5-pro-exp-0801输出经常被截断

### ISSUE THREAD

**Issue by SailFlorve** [Calcium-Ion/new-api#407]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gemini-1.5-pro-exp-0801输出经常被截断，传max_tokens也没有用

**Comment by RedwindA** [comment]
免费key 不能设置安全等级为 None ，输出被审核了

**Comment by SailFlorve** [comment]
> 免费key 不能设置安全等级为 None ，输出被审核了

并非此原因。设置了GEMINI_SAFETY_SETTING=BLOCK_ONLY_HIGH后，还是输出特定的长度被截断了，一般都是350左右的token
