### ISSUE TITLE
系统设置中的worker代理设置是否只在处理图片时有效？

### ISSUE THREAD

**Issue by tempppabx1** [Calcium-Ion/new-api#412]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在启用 系统设置 -- 代理设置 中的代理后，一般的请求没有走代理，通过查看源码发现worker代理好像仅在处理一些图片时生效，而非全局请求代理，这是一个有意为之的特性吗

**复现步骤**
启用 系统设置 -- 代理设置中的代理

**预期结果**
全局请求代理

**Comment by Calcium-Ion** [comment]
只能代理图片，代理请求将违反cf的协议
