### ISSUE TITLE
支持一下识别文件的功能吧，按最高收费标准设置就不会出现争议了。或者后台设置一个开关，可以选择支持文件识别。或者不支持。现在多模态的模型越来越多，文件识别我觉得很有必要加个。

### ISSUE THREAD

**Issue by arelice** [Calcium-Ion/new-api#414]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by Calcium-Ion** [comment]
你这个需求是哪个模型供应商的文件识别功能，可以按需按供应商类型单独适配

**Comment by arelice** [comment]
> 你这个需求是哪个模型供应商的文件识别功能，可以按需按供应商类型单独适配

我觉得最好是每个提供商都支持，隔壁chatapi好像就是支持视觉模型的都可以识别文件。不过我用惯newapi了。不太想换。所以就提了个isure。可以识别文件的模型，用new中转了一下就不能识别文件了，就总觉得不完美。美女 加油

**Comment by Calcium-Ion** [comment]
你真要支持识图你可以用现在的环境变量都改成false
GET_MEDIA_TOKEN：是统计图片token，默认为 true，关闭后将不再在本地计算图片token，可能会导致和上游计费不同，此项覆盖 GET_MEDIA_TOKEN_NOT_STREAM 选项作用。
GET_MEDIA_TOKEN_NOT_STREAM：是否在非流（stream=false）情况下统计图片token，默认为 true。
我不想弄成他们那样
