### ISSUE TITLE
Unknown parameter: 'stream_options'

### ISSUE THREAD

**Issue by kenneth-bro** [Calcium-Ion/new-api#418]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
版本:  v0.2.7.4

通过平台调用  gpt-4o-mini 模型的时候，报错以下内容：
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "Unknown parameter: 'stream_options'. (request id: 20240806214436917505976hvsFC5y2) (request id: 20240806214435144343103vXhjiHlZ)", 'type': 'invalid_request_error', 'param': 'stream_options', 'code': 'unknown_parameter'}}
```

但是我直接通过openai的sdk调用上游的API，是不会报错的。
```
stream_completion = client.chat.completions.create(
    model=model,
    messages=messages,
    stream=True
)

print("以下为Stream输出:")
for chunk in stream_completion:
    if chunk.choices[0].finish_reason == "stop":
        # 完成
        break

    chunk_text = chunk.choices[0].delta.content
    if chunk_text is not None:
        print(f"接收到: {chunk_text}")
```

是否平台默认加入了 stream_option的参数？上游不支持这个参数就会报错。

**复现步骤**

**预期结果**

正确输出

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
new的最新版本会根据渠道是否支持'stream_options'来决定要不要传这个参数，你应该问你的上游
