### ISSUE TITLE
增强支持qwen-vl-plus多模型模型

### ISSUE THREAD

**Issue by Liyu910228** [Calcium-Ion/new-api#421]
目前国内多模态模型只要阿里做的最好，把多模态模型支持了，感觉这个就上了一个台阶，我在one-api中也提了这个问题，作者也回复了，说在他的计划中，但是好久没有动静

**Comment by Calcium-Ion** [comment]
经测试是支持的，你说的是什么不支持
![image](https://github.com/user-attachments/assets/190d2bc2-ae9f-4ecd-b35a-fe1a6f7e2a37)

**Comment by ribun123** [comment]
好像不支持 视觉推理模型 qvq-max系列
