### ISSUE TITLE
渠道的分组筛选不能正常筛选渠道同时属于多个分组的情况

### ISSUE THREAD

**Issue by Yan-Zero** [Calcium-Ion/new-api#423]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道界面的分组，当渠道同时属于多个分组的时候，筛选不能正常运作。

**复现步骤**
MySQL 数据库，一个渠道选择多个分组
筛选后会发现无法正常过滤出来

**相关截图**
![image](https://github.com/user-attachments/assets/933d2dba-6fbf-46f2-b93c-d94c0d5f7cef)
![5ce42270d5d3974f9334b60169c6c69d](https://github.com/user-attachments/assets/50378245-994e-4ecf-879c-493a51c73929)
![7adba12ce059a3cfd24007a3250c7027](https://github.com/user-attachments/assets/752f129f-b69d-4a2f-9840-5419532a1cdf)

**Comment by fevrax** [comment]
下一版修改了 #425

**Comment by dalefengs** [comment]
#425
