### ISSUE TITLE
LOBEHUB无法在new-api中带令牌直接进入，需要手动复制令牌

### ISSUE THREAD

**Issue by sheongkamyu** [Calcium-Ion/new-api#430]
LOBEHUB无法在new-api中带令牌直接进入，需要复制令牌，其他chatgpt-next等可以。

![image](https://github.com/user-attachments/assets/cbc12e68-e70b-4e63-9d42-a475f0eef6b2)
![image](https://github.com/user-attachments/assets/1587b683-d96f-4502-9505-3a1b7d1a0182)

**Comment by AthanaD** [comment]
这个之前半年前我也有给作者反馈过，作者好像说要找Lobe那边才能解决，应该是作者不太懂Lobe Chat相关代码如何自动化带密钥进入。目前最新的状态我看还是没有解决，都是需要手动复制令牌才能回答问题的

**Comment by AthanaL** [comment]
期待项目主早日解决这个BUG吧

**Comment by HynoR** [comment]
看你截图在用错误的参数，新版lobe令牌参数实际上要这样的格式才可以导入。新格式为
```
https://foo.bar/?settings={"keyVaults":{"openai":{"apiKey":"114514","baseURL":"https://1919.810"}},"languageModel":{"openai":{"fetchOnClient":false}}}
```

**Comment by AthanaL** [comment]
> 看你截图在用错误的参数，新版lobe令牌参数实际上要这样的格式才可以导入。新格式为
> 
> ```
> https://foo.bar/?settings={"keyVaults":{"openai":{"apiKey":"114514","baseURL":"https://1919.810"}},"languageModel":{"openai":{"fetchOnClient":false}}}
> ```

你看下别人说的是在new-api导入无法复制令牌进入，跟这个链接没什么关系啊  在new-api里边是通过点击令牌进入

**Comment by jimmyshjj** [comment]
你是指你在“运营设置”中填入了你自己的lobechat，然后在令牌页面直接点聊天，lobechat没有填入对应令牌？

**Comment by AthanaL** [comment]
> 你是指你在“运营设置”中填入了你自己的lobechat，然后在令牌页面直接点聊天，lobechat没有填入对应令牌？

对啊，new-api都是这样进入网站啊  可以带令牌自动复制进入next网站，就是LobeCHAT不行

**Comment by jimmyshjj** [comment]
> > 你是指你在“运营设置”中填入了你自己的lobechat，然后在令牌页面直接点聊天，lobechat没有填入对应令牌？
> 
> 对啊，new-api都是这样进入网站啊 可以带令牌自动复制进入next网站，就是LobeCHAT不行

最直接的解决方式是设置内填nextchat，如要用lobechat需要在“聊天”按钮右侧的下拉菜单中选择lobechat。
原因在于“聊天”按钮会传递nextchat格式的配置。lobechat选择不使用nextchat的格式，自己新建了一套。

**Comment by AthanaD** [comment]
> > 看你截图在用错误的参数，新版lobe令牌参数实际上要这样的格式才可以导入。新格式为
> > ```
> > https://foo.bar/?settings={"keyVaults":{"openai":{"apiKey":"114514","baseURL":"https://1919.810"}},"languageModel":{"openai":{"fetchOnClient":false}}}
> > ```
> 
> 你看下别人说的是在new-api导入无法复制令牌进入，跟这个链接没什么关系啊 在new-api里边是通过点击令牌进入

假设我的LOBECHAT网站为https://web.xxxx.com/chat，现在我利用如下规则：
![image](https://github.com/user-attachments/assets/889cab06-f0b1-45a5-8904-82302fa19136)
应该在下边的链接里边怎么填？
