### ISSUE TITLE
gpt-4o-2024-08-06模型补全倍率错误，无法修改

### ISSUE THREAD

**Issue by hcppxgit** [Calcium-Ion/new-api#435]
![197101d5-abbe-49e8-a299-79978e267190](https://github.com/user-attachments/assets/cbde96e5-b9d5-4013-b800-a6d89cefd09d)
官方标准输入2.5输出10

计算出来的模型倍率是1.25，补全倍率是4，但现有版本2.7.4a4的补全倍率是3，且无法自定义修改。

**Comment by Calcium-Ion** [comment]
最新版补全倍率就是4，请更新到最新版

**Comment by hcppxgit** [comment]
> 最新版补全倍率就是4，请更新到最新版

New API v0.2.7.4-alpha.4 刚更新的。这个的arm版本难道还不是最新？

**Comment by Calcium-Ion** [comment]
arm请自己构建

**Comment by hcppxgit** [comment]
> arm请自己构建

抱歉我是新手不太熟悉，麻烦帮看看gpt给我说的方法对不对：

以下是从克隆项目到构建Docker镜像的一系列步骤：
### 1. 安装Docker

首先，确保你的Ubuntu服务器上已经安装了Docker。如果还没有安装，你可以通过以下命令安装Docker：

```bash
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt update
sudo apt install docker-ce
```

安装后，通过运行 `sudo systemctl status docker` 来检查Docker服务是否正在运行。

### 2. 克隆项目

接下来，使用`git`克隆项目到你的服务器。如果你的服务器还没有安装`git`，可以通过运行`sudo apt install git`来安装。

然后，克隆项目到你选择的目录，例如：

```bash
git clone <项目的GitHub URL>
cd <克隆下来的项目目录>
```

请将`<项目的GitHub URL>`替换为实际的项目URL，将`<克隆下来的项目目录>`替换为实际的项目目录名。

### 3. 构建Docker镜像

在项目根目录下，你应该能找到`Dockerfile`。运行以下命令来构建Docker镜像：

```bash
docker build -t <镜像名>:<标签> .
```

这里，`<镜像名>`是你给镜像起的名字，`<标签>`是你给镜像指定的标签，通常用于版本控制，例如`latest`。点号`.`表示Dockerfile位于当前目录。

例如，如果你想将镜像命名为`my-app`，并标记为`latest`，则命令如下：

```bash
docker build -t my-app:latest .
```

构建过程可能会花费一些时间，因为它需要下载基础镜像、安装依赖、编译代码等。

### 4. 运行Docker容器

构建完成后，你可以通过以下命令来运行Docker容器：

```bash
docker run -d -p 3000:3000 --name <容器名> <镜像名>:<标签>
```

这里，`-d`表示以后台模式运行容器，`-p 3000:3000`表示将容器的3000端口映射到宿主机的3000端口，`--name <容器名>`是给容器指定的名称，`<镜像名>:<标签>`是你之前构建的镜像。

例如，要运行名为`my-app-container`的容器，可以使用以下命令：

```bash
docker run -d -p 3000:3000 --name my-app-container my-app:latest
```

### 5. 验证

构建和运行容器后，你可以通过访问`http://<你的服务器IP或域名>:3000`来验证应用是否正常运行。

以上就是在Ubuntu服务器上从克隆项目到构建和运行Docker容器的完整步骤。如果在过程中遇到任何问题，可以查阅相关的Docker和Git文档，或者在社区中寻求帮助。

**Comment by Calcium-Ion** [comment]
v0.2.7.6-alpha.4的arm版本在构建，你等等吧

**Comment by hcppxgit** [comment]
> v0.2.7.6-alpha.4的arm版本在构建，你等等吧

好的，太感谢了。因为之前都是用这个：docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower -cR命令来一键更新的，突然要自己构建还真弄不来，谢谢了。
