### ISSUE TITLE
兼容siliconflow的Rerank

### ISSUE THREAD

**Issue by xy3xy3** [Calcium-Ion/new-api#437]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

文档地址

https://docs.siliconflow.cn/reference/creatererank-1

测试直接选openai接入后说未实现

```
$ curl --request POST \
     --url https://newapi域名/v1/rerank \
     --header 'accept: application/json' \
     --header 'authorization: Bearer sk-xxx' \
     --header 'content-type: application/json' \
     --data '
{
  "model": "BAAI/bge-reranker-v2-m3",
  "query": "Apple",
  "documents": [
    "苹果",
    "香蕉",
    "水果",
    "蔬菜"
  ],
  "top_n": 4,
  "return_documents": false,
  "max_chunks_per_doc": 1024,
  "overlap_tokens": 80
}
'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   379  100   151  100   228     97    147  0:00:01  0:00:01 --:--:--   245{"error":{"message":"not implemented (request id: 20240815175815741360656uYIfGCmK)","type":"new_api_error","param":"","code":"convert_request_failed"}}
```

**应用场景**

用于重排

**Comment by Calcium-Ion** [comment]
能否提供测试密钥

**Comment by xy3xy3** [comment]
> 能否提供测试密钥

我不是官方人员哎，麻烦您注册个账号呗，他们现在注册了就可以直接用key，rerank是免费的

**Comment by Calcium-Ion** [comment]
一看要手机号就不想注册了，通过谷歌登录还非得我验证手机🤣🤣🤣

**Comment by sabibi12** [comment]
sk-tkbqqsgkoqkjhglmxwbpywfxxcsyxrtjqyybgfagnbuaaerj
我提供一个14元额度的key，公开后应该很快就要被刷完了，希望作者尽快使用

**Comment by xy3xy3** [comment]
> sk-tkbqqsgkoqkjhglmxwbpywfxxcsyxrtjqyybgfagnbuaaerj 我提供一个14元额度的key，公开后应该很快就要被刷完了，希望作者尽快使用

要不你开个新的 这个close了不知道作者看不看的了

**Comment by sabibi12** [comment]
> > sk-tkbqqsgkoqkjhglmxwbpywfxxcsyxrtjqyybgfagnbuaaerj 我提供一个14元额度的key，公开后应该很快就要被刷完了，希望作者尽快使用
> 
> 要不你开个新的 这个close了不知道作者看不看的了

好的
