### ISSUE TITLE
什么时候编辑渠道的时候能看到密钥啊？

### ISSUE THREAD

**Issue by 3377** [Calcium-Ion/new-api#449]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
日常的API来源乱七八糟，修改的时候看不到API的密钥，根本没法测试

**应用场景**

**Comment by Calcium-Ion** [comment]
这本来就是特性，以后也不会改成能看到密钥的

**Comment by 3377** [comment]
不能定义为变量，让人选择是否开启吗。。。。

**Comment by Calcium-Ion** [comment]
不能，特殊需求自己二开
