### ISSUE TITLE
Claude 渠道，没有对 Tool 的 role 进行处理

### ISSUE THREAD

**Issue by Yan-Zero** [Calcium-Ion/new-api#454]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

OpenAI 格式的 Tool Calls，返回结果再次提交给AI使用的 role 是 tool
而 Claude 则是使用 user 作为 role，整了一个特殊的 content 类型来提交
```
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "tool_result",
                            "tool_use_id": tool_use.id,
                            "content": tool_result,
                        }
                    ],
                },
```

NewAPI 目前并没有处理 tool role 的转发

**Comment by jiusheng6** [comment]
希望添加一个转换：我用python搞得def convert_function_to_tool_result(messages):
    converted_messages = []
    for msg in messages:
        if msg.get('role') == 'function':
            converted_messages.append({
                'role': 'user',
                'content': json.dumps({
                    'type': 'tool_result',
                    'tool_use_id': 'dummy_id',
                    'content': msg['content']
                })
            })
        else:
            converted_messages.append(msg)
    return converted_messages

**Comment by jiusheng6** [comment]
希望合并进去
