### ISSUE TITLE
nginx 设置了反向代理，使用域名作为 api 代理地址后，出现截图所示错误

### ISSUE THREAD

**Issue by sun-i** [Calcium-Ion/new-api#46]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/Calcium-Ion/new-api/assets/111034439/87532fb6-13df-48ae-99ff-5d7a524b63f9)

如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
请使用最新代码构建或者使用calciumion/new-api:0.1.2-alpha.1
