### ISSUE TITLE
请求延迟高问题

### ISSUE THREAD

**Issue by KamiPasi** [Calcium-Ion/new-api#465]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当数据库延迟比较高的时候, 请求延迟也会变高, 即使开了redis的情况下
怀疑可能是因为每次请求都会同步用户余额造成的
让gpt分析了一下不知道对不对:
### 延迟问题分析:

- `CacheGetUserQuota` 运行时通常不会受到 `CacheUpdateUserQuota` 的直接影响，除非两个操作在同一个 Redis 键上竞争读写。
- 如果 `CacheUpdateUserQuota` 正在写 Redis 缓存，而此时 `CacheGetUserQuota` 正在读相同的缓存键，可能会发生一定的延迟，因为 Redis 是单线程处理命令的客户端线程。

### 延迟的具体情形:

1. **同时操作（竞争读写）**:
   - 如果 `CacheUpdateUserQuota` 正在写入数据，且这个过程需要一点时间（如数据库读操作），此时有可能 `CacheGetUserQuota` 会稍微等待写操作的完成。

2. **一般情况下**:
   - 大多数情况下，这两个操作并不会显著影响对方的性能，除非在极端高并发场景中，都操作相同的缓存键。

**Comment by Calcium-Ion** [comment]
肯定是您自己的配置问题而不是redis的问题

**Comment by KamiPasi** [comment]
> 肯定是您自己的配置问题而不是redis的问题

啥配置, 我没改过redis的配置
