### ISSUE TITLE
限制模型令牌的功能無法正確實現

### ISSUE THREAD

**Issue by 123hi123** [Calcium-Ion/new-api#466]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
限制模型令牌的功能無法正確實現
**复现步骤**
![image](https://github.com/user-attachments/assets/5ce580b1-94ce-4f70-b1ee-d33c286849a7)
對這個令牌做上限制
再open webui中使用
會得到下面的沒有限制住的結果 
![image](https://github.com/user-attachments/assets/42f4b8ac-133f-49d4-a9ff-e1828c30613b)
**预期结果**
會讓open webui得到限制過後的模型列表

**Comment by Calcium-Ion** [comment]
![image](https://github.com/user-attachments/assets/35b8ed38-efc6-4b2b-b03f-458659066448)
![image](https://github.com/user-attachments/assets/dcf426ef-f1da-4d63-b832-38056b7f7620)

测试无法复现

**Comment by 123hi123** [comment]
> ![image](https://private-user-images.githubusercontent.com/61247483/364772632-35b8ed38-efc6-4b2b-b03f-458659066448.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTgwMjIsIm5iZiI6MTcyNTU1NzcyMiwicGF0aCI6Ii82MTI0NzQ4My8zNjQ3NzI2MzItMzViOGVkMzgtZWZjNi00YjJiLWIwM2YtNDU4NjU5MDY2NDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE3MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MmVhZGExZTI0YjBmMGNlYjYwNGY1MTgxNjFmMDE5MTlhYzM3MjJlZGNlZGRhYjYxMjAzMDMwZDgyMmExYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._OKBBAwd5ehDXfLnmMiz3dEy_BsxrVl6tVNgBFDKYSc) ![image](https://private-user-images.githubusercontent.com/61247483/364772701-dcf426ef-f1da-4d63-b832-38056b7f7620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTgwMjIsIm5iZiI6MTcyNTU1NzcyMiwicGF0aCI6Ii82MTI0NzQ4My8zNjQ3NzI3MDEtZGNmNDI2ZWYtZjFkYS00ZDYzLWI4MzItMzgwNTZiN2Y3NjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDE3MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYjhmN2VlYWFlYWZlYzg0ZTFiMzMxMDRiOGVmNzE0MTcwNGM0MmJjOGJmZWM5ZjQzNzMwZDk2MmY3NDA0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MxUtFXf2EvFPDJwadSopyWFAVo7QNGMp1dcj9Fc6t-E)
> 
> 测试无法复现

嗯，它會產生這樣的bug前提是你的渠道，當中要有人去提供這樣的一個模型
打個比方說你有一個渠道，有提供 claude 的模型，然後另外一個提供 gpt 的模型
然後你有一個令牌限制，只能用 gpt 的模型
這個時候，如果你用 models 去抓的話，會抓到兩個模型
可能再麻煩你試試看了

**Comment by Calcium-Ion** [comment]
我的渠道肯定是有claude-3-5-sonnet-20240620这个模型的

**Comment by 123hi123** [comment]
> 我的渠道肯定是有claude-3-5-sonnet-20240620这个模型的

那我下午的時候用你的方法測試一下
目前猜測是open webui 連false的模型也會抓 🤔

**Comment by 123hi123** [comment]
嗯，這個 bug 要產生是請求頭 models 才會發生
使用到的測試代碼如下 記得填入你自己的呃認證的 key
# 可能需要的認證token
headers["Authorization"] = ""
```import requests
from tabulate import tabulate

# 設置API的基礎URL
base_url = "http://localhost:9090/v1"

# 設置headers
headers = {
    "Content-Type": "application/json"
}

# 可能需要的認證token
headers["Authorization"] = ""

def get_models():
    try:
        response = requests.get(f"{base_url}/models", headers=headers)
        response.raise_for_status()  # 如果請求不成功則拋出異常
        return response.json()
    except requests.RequestException as e:
        print(f"發生錯誤: {e}")
        return None

# 執行請求並處理結果
models = get_models()
if models and 'data' in models:
    # 提取所有模型的id
    model_ids = [model['id'] for model in models['data']]
    
    # 使用tabulate創建一個漂亮的表格
    table = tabulate([[id] for id in model_ids], headers=['Model ID'], tablefmt='fancy_grid')
    
    print("可用的模型:")
    print(table)
else:
    print("無法獲取模型列表或列表為空。")```
  以下截取一部分的返回結果
  裏面可以清楚的看到有一些我沒有允許通過的模型
  
![image](https://github.com/user-attachments/assets/a2f50e93-acfb-470a-a165-d99b4ee69065)
![image](https://github.com/user-attachments/assets/20b32b0b-fea2-4098-a83d-db3d07ff4c55)
我有且僅有這一個 api key

**Comment by 123hi123** [comment]
@Calcium-Ion

**Comment by Yan-Zero** [comment]
模型列表获取和能否请求是两码事，而且OpenWebUI本身支持白名单模型

**Comment by 123hi123** [comment]
> 模型列表获取和能否请求是两码事，而且OpenWebUI本身支持白名单模型

多謝回覆 看來是我描述錯誤issues 那想問一下 new api之後可能會支持把models接口所展示出來的模型列表也一併限制嗎

**Comment by Calcium-Ion** [comment]
> > 模型列表获取和能否请求是两码事，而且OpenWebUI本身支持白名单模型
> 
> 多謝回覆 看來是我描述錯誤issues 那想問一下 new api之後可能會支持把models接口所展示出來的模型列表也一併限制嗎

你应该重新开一个issue描述这个问题

**Comment by 123hi123** [comment]
好
