### ISSUE TITLE
新增stripe支付功能

### ISSUE THREAD

**Issue by crazymsn** [Calcium-Ion/new-api#468]
大佬能否在原来易支付渠道下，新增stripe支付方式呀？

**Comment by LemonZuo** [comment]
可以去看下linux-do/new-api,已经有实现

**Comment by crazymsn** [comment]
麻烦发一下项目地址

**Comment by LemonZuo** [comment]
你可以直接在本项目里面的fork里面找

**Comment by crazymsn** [comment]
并没有stripe，搭建了...支付宝和微信都不支持

**Comment by crazymsn** [comment]
![Uploading 屏幕截图 2024-09-12 142816.png…]()

**Comment by LemonZuo** [comment]
![image](https://github.com/user-attachments/assets/e2926fce-604c-42cc-ab3c-efed0fc7dcba)
确定有认真看吗

**Comment by crazymsn** [comment]
哦哦，我看到啦！

**Comment by crazymsn** [comment]
不过，支付宝和微信好像这个没有支持，还是需要跳转发卡网

**Comment by LemonZuo** [comment]
要同时兼容，那就只能等大佬们开发了，或者直接用stripe的微信和支付宝支付

**Comment by moylor123** [comment]
为什么stripe 手机端不显示，充值按钮？
