### ISSUE TITLE
渠道ID不正常增加

### ISSUE THREAD

**Issue by NooAcc** [Calcium-Ion/new-api#470]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

新增渠道的时候，渠道的ID有时候会变得特别大

**复现步骤**

出现得并不规律，所以暂时不知道如何复现
我在想是不是因为我用的是远程数据库，之前用本地数据库就没这问题

**预期结果**

**相关截图**
![image](https://github.com/user-attachments/assets/0b07feb5-4a25-4568-8cf2-01a1f9f7e002)

**Comment by Calcium-Ion** [comment]
你是不是手动改过渠道id

**Comment by NooAcc** [comment]
> 你是不是手动改过渠道id

在ID出现异常之后，我试过手动修改渠道ID，
之后发现这么干治标不治本，就把数据库+docker容器全删掉了🤓

目前用的是新建的容器+数据库，渠道ID的问题依然存在😭

**Comment by Calcium-Ion** [comment]
因为mysql会从你曾经改过最大的id自增

**Comment by NooAcc** [comment]
> 因为mysql会从你曾经改过最大的id自增

对的，所以我才说这么干治标不治本🤓

**Comment by NooAcc** [comment]
我感觉可能是这个数据库有问题

刚才我又新建了个渠道，ID变成了90001，然而在这之前我没有进行任何操作😭
