### ISSUE TITLE
优化一下失败重试逻辑

### ISSUE THREAD

**Issue by bingloo** [Calcium-Ion/new-api#475]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
优化一下当前失败重试逻辑，目前的方案是在同优先级只重试一次，然后依次减少一个优先级。
理想的方式：重试当前优先级下的所有渠道，然后依次往下一个优先级重试所有渠道，直到成功。
**应用场景**
失败重试。

**Comment by Calcium-Ion** [comment]
我觉得现在的重试逻辑没问题，你这个逻辑把权重放哪去了

**Comment by kuangxiaoye** [comment]
目前的重试逻辑没问题，不需要任何更改
