### ISSUE TITLE
用户可选分组删除后，用户已有令牌仍能使用

### ISSUE THREAD

**Issue by wang0yue** [Calcium-Ion/new-api#477]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
用户可选分组有default和vip时，用普通用户创建一个vip令牌，然后把用户可选分组的vip删了，用户已有vip分组的令牌仍能使用
**复现步骤**

**预期结果**
用户已有vip分组的令牌不能使用

**Comment by Calcium-Ion** [comment]
是没办法使用的，你自己测试一下调用不就知道了
