### ISSUE TITLE
models 限制功能失敗

### ISSUE THREAD

**Issue by 123hi123** [Calcium-Ion/new-api#481]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
已經更新到 最新的鏡像 但是無法使用
**复现步骤**
創建一個令牌限制一個模型可用
**预期结果**
在api checker 中 顯示一個模型
**相关截图**
![image](https://github.com/user-attachments/assets/a50cf38b-3387-44f8-8d90-daf04081588e)
![image](https://github.com/user-attachments/assets/99c25c70-3c55-415a-b3e1-326f581cef56)
![image](https://github.com/user-attachments/assets/9fc7a6b9-b4b2-4660-a007-54d5532cd1e5)

**Comment by Calcium-Ion** [comment]
你的这个界面不是最新版，麻烦再更新一下看看

**Comment by Calcium-Ion** [comment]
不过现在更新了新功能，又有新的问题了。

**Comment by Calcium-Ion** [comment]
目前最新版对于模型限制获取的models是正确的

**Comment by 123hi123** [comment]
剛剛測了一下還是一樣
用的是 docker pull calciumion/new-api:latest 拉的最新鏡像 因為另一個指令不知道為甚麼更新都會失敗

**Comment by Calcium-Ion** [comment]
那你现在显示的版本是多少

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/15a67cc3-ab50-4c27-9397-28ca977df4f5)
確實是舊的 但我實在不知道為啥都拉不到 問了ai就說是網路問題
![image](https://github.com/user-attachments/assets/bafce599-47c5-484a-8ea5-57c359b7ff7a)

**Comment by Calcium-Ion** [comment]
你用docker pull calciumion/new-api:latest的话提示什么

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/433e872f-4773-404d-af74-5f6ff9d65d6b)
感謝作者協助 提示長這樣

**Comment by Calcium-Ion** [comment]
你拉取的镜像确实是最新版，但是你没有成功更新容器的镜像版本

**Comment by Calcium-Ion** [comment]
如果是docker compose的话，需要docker-compose up -d
如果是直接启动容器的话，需要删除容器重建

**Comment by 123hi123** [comment]
成功辣 多謝作者
