### ISSUE TITLE
除了open ai 以外增加其他渠道模型的重定向

### ISSUE THREAD

**Issue by 123hi123** [Calcium-Ion/new-api#483]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
可以重定向模型名稱
**应用场景**
像github models 對於上下文有所限制就可以讓他不要混在其他4o模型裡面
當然也不撇除我亂用重定向導致的重定向失敗
![image](https://github.com/user-attachments/assets/d22cca67-7f87-4443-8ecc-a691b903f706)
反向使用的話會有以下效果
![image](https://github.com/user-attachments/assets/b591a0f5-c9b2-44c2-8190-3f86dd9bb8cb)

**Comment by Calcium-Ion** [comment]
你自己重定向没玩懂

**Comment by 123hi123** [comment]
那我可以請教一下作者怎麼使用這個重定向嗎 確實是我沒玩明白

**Comment by 123hi123** [comment]
我玩懂了 攢的
