### ISSUE TITLE
令牌分组无法做到渠道隔离，希望给个开关能改回以前一样

### ISSUE THREAD

**Issue by hcppxgit** [Calcium-Ion/new-api#485]
**问题描述**

开发者您好，打扰了，我有特定的渠道只想给特定的用户组使用，希望能可变回之前那样用户组和渠道之间一一对应隔离开来，让VIP组只能创建VIP组的令牌，默认组用户只能创建默认组令牌，以此来做到渠道隔离，现在的情况是：

如果把【用户可选分组】里只留下一个默认组，VIP用户组创建的令牌也只能是默认，不能选VIP渠道。

如果把【用户可选分组】设为可选多个分组，那么默认用户组会创建VIP的令牌来霍霍VIP的渠道。

例如默认组可能会来些乱七八糟的人搞瑟瑟，那么我只给他用cohere和一些垃圾渠道，因为可能他问的问题在别的渠道会被审计不合时宜。
正常人就用VIP渠道。

**复现步骤**
直接创建一个别的分组令牌即可用别的分组渠道，用户分组失去了原本的隔离渠道的作用。

**预期结果**
给个开关，可改回以前的逻辑，让用户组创建的令牌只能调用自己对应用户组的渠道。
即：
默认组用户仅能创建默认令牌，仅能使用默认渠道。
VIP组用户仅能创建VIP令牌，仅能使用VIP渠道。

**Comment by Calcium-Ion** [comment]
你把运营设置里的用户可选分组删掉不就行了吗

**Comment by hcppxgit** [comment]
> 你把运营设置里的用户可选分组删掉不就行了吗

删掉以后就是所有令牌都是默认分组，VIP组就无法创建VIP令牌了啊。

**Comment by hcppxgit** [comment]
> 你把运营设置里的用户可选分组删掉不就行了吗

我现在的情况是，把有1个玩酒馆的人丢在SVIP，给他只用几个特定渠道。如果删掉，他就可以创建默认令牌，霍霍其他渠道了。

**Comment by Calcium-Ion** [comment]
只是描述的问题。默认分组的意思是用户的分组

**Comment by Calcium-Ion** [comment]
vip分组无法创建默认分组的令牌

**Comment by hcppxgit** [comment]
> 只是描述的问题。默认分组的意思是用户的分组

原来是描述问题，感谢解惑，我还以为默认分组就是可以调用默认渠道。
