### ISSUE TITLE
绘图不返回图片，Discord中有图片

### ISSUE THREAD

**Issue by jokenee** [Calcium-Ion/new-api#486]
new-api  | [GIN] 2024/09/19 - 03:02:57 | 20240919030257156536191BVP5pPCI | 204 |      28.917µs | 162.158.106.164 | OPTIONS /mj/submit/imagine
new-api  | [INFO] 2024/09/19 - 03:02:57 | 20240919030257223193010lOFwzMho | user 1 quota 241017297 and token 1619 quota 499889 are enough, trusted and no need to pre-consume 
new-api  | [INFO] 2024/09/19 - 03:02:57 | 20240919030257223193010lOFwzMho | record consume log: userId=1, 用户调用前余额=241017297, channelId=1, promptTokens=22, completionTokens=3, modelName=gpt-4o-mini, tokenName=midjourney-proxy-prompt翻译, quota=5, content=模型倍率 0.07，补全倍率 4.00，分组倍率 2.00 
new-api  | [GIN] 2024/09/19 - 03:02:57 | 20240919030257223193010lOFwzMho | 200 |  549.312532ms |   172.71.82.135 |    POST /v1/chat/completions
new-api  | 2024/09/19 03:02:57 respStr: {"code":1,"description":"提交成功","result":"1726686177195433","properties":{"discordInstanceId":"1285977394112495752"}}
new-api  | 
new-api  | 2024/09/19 03:02:57 /build/model/midjourney.go:148 Error 1366: Incorrect string value: '\xE7\xBE\x8E\xE5\xA5\xB3...' for column 'prompt' at row 1
new-api  | [1.328ms] [rows:0] INSERT INTO `midjourneys` (`code`,`user_id`,`action`,`mj_id`,`prompt`,`prompt_en`,`description`,`state`,`submit_time`,`start_time`,`finish_time`,`image_url`,`status`,`progress`,`fail_reason`,`channel_id`,`quota`,`buttons`,`properties`) VALUES (1,1,'IMAGINE','1726686177195433','美女秃头
new-api  |  --v 6 --ar 1:1','','提交成功','',1726686177791,0,0,'','','0%','',4,100000,'','')
new-api  | [INFO] 2024/09/19 - 03:02:57 | 2024091903025717950479651IC212j | record consume log: userId=1, 用户调用前余额=241017297, channelId=4, promptTokens=0, completionTokens=0, modelName=mj_imagine, tokenName=test, quota=100000, content=模型固定价格 0.10，分组倍率 2.00，操作 IMAGINE，ID 1726686177195433 
new-api  | 2024/09/19 03:02:57 &{4 insert_midjourney_task_failed <nil> }
new-api  | [ERR] 2024/09/19 - 03:02:57 | 2024091903025717950479651IC212j | relay error (channel #4, status code 400): insert_midjourney_task_failed  
new-api  | [GIN] 2024/09/19 - 03:02:57 | 2024091903025717950479651IC212j | 400 |  651.636818ms | 162.158.106.164 |    POST /mj/submit/imagine
new-api  | [GIN] 2024/09/19 - 03:02:58 | 20240919030258587639653NPdkgH1F | 200 |     792.479µs |             ::1 |     GET /api/status
new-api  | [SYS] 2024/09/19 - 03:03:05 | syncing tokens from database 
new-api  | [SYS] 2024/09/19 - 03:03:05 | syncing options from database 
new-api  | [SYS] 2024/09/19 - 03:03:05 | syncing channels from database 
new-api  | [SYS] 2024/09/19 - 03:03:05 | channels synced from database 

![image](https://github.com/user-attachments/assets/f29cb0b2-f9fb-444c-abc5-7c2ea3865100)

**Comment by Calcium-Ion** [comment]
你的数据库编码有问题，不支持中文

**Comment by jokenee** [comment]
> 你的数据库编码有问题，不支持中文
谢谢了
有数字钱包吗，我给你打点U
