### ISSUE TITLE
模型价格列表添加令牌分组查看

### ISSUE THREAD

**Issue by KarlLee830** [Calcium-Ion/new-api#487]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望在模型价格列表添加令牌分组查看功能，可选择令牌分组，查看选中的令牌分组可用的模型与信息

**Comment by Calcium-Ion** [comment]
晚点会加上

**Comment by buwanyuanshen** [comment]
还有个小bug，现在设置中的default对应的是默认分组，实际上应该为用户分组是默认分组，这会导致vip分组创建默认的令牌使用的渠道是default而不是vip分组的渠道。

**Comment by Calcium-Ion** [comment]
> 还有个小bug，现在设置中的default对应的是默认分组，实际上应该为用户分组是默认分组，这会导致vip分组创建默认的令牌使用的渠道是default而不是vip分组的渠道。

并没有这种bug，令牌的默认分组指的是用户的分组，而不是分组default
