### ISSUE TITLE
grok怎么设置？

### ISSUE THREAD

**Issue by ench2** [Calcium-Ion/new-api#496]
**例行检查**
用自定义模型 baseurl设置成 https://api.groq.com/openai/v1 不行
这个地址在ollama里是正常运行的

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by SzeMeng76** [comment]
https://api.groq.com/openai/v1/chat/completions 完整baseurl是这个 测试了没问题

**Comment by 123hi123** [comment]
為什麼不多嘗試一下
正確答案是把openai/v1去掉
