### ISSUE TITLE
微信扫码登录无法进入令牌页面(首次异常，刷新后正常)

### ISSUE THREAD

**Issue by hp0912** [Calcium-Ion/new-api#501]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

微信登录和账号密码登录行为不一致

账号密码登录默认进入令牌页面

微信登录默认进入首页

致命问题是微信登录`首次`进入令牌页面后会提示未登录

**复现步骤**

微信扫码登录 -> 点击`令牌`进入令牌页面 -> 提示需要登录

**预期结果**

微信扫码登录能正常进入令牌页面

**相关截图**

![WX20240923-105550@2x](https://github.com/user-attachments/assets/36722631-d7f9-4d69-9787-b4c59c18ed1c)

**Comment by Calcium-Ion** [comment]
最新版已修复，可以试一下
[fix: 第三方登录注销](https://github.com/Calcium-Ion/new-api/commit/972ac1ee0f72d485bf99a2740f911f0658009d30) https://github.com/Calcium-Ion/new-api/issues/500

**Comment by hp0912** [comment]
> 最新版已修复，可以试一下 [fix: 第三方登录注销](https://github.com/Calcium-Ion/new-api/commit/972ac1ee0f72d485bf99a2740f911f0658009d30) #500

是的，已经修复了
