### ISSUE TITLE
使用Playground时会弹出undefined以及气泡超出边界的问题

### ISSUE THREAD

**Issue by Nightrain0** [Calcium-Ion/new-api#511]
如图：
![image](https://github.com/user-attachments/assets/9a7547ef-6651-4340-9126-238db80fc631)

**Comment by Nightrain0** [comment]
![image](https://github.com/user-attachments/assets/049fe310-2420-4018-982c-b41ccd290b1d)
画图会出现气泡超出边界的问题。

**Comment by wang0yue** [comment]
+希望进去使用的是用户默认分组

**Comment by Calcium-Ion** [comment]
气泡问题无法复现
