### ISSUE TITLE
负载均衡

### ISSUE THREAD

**Issue by maoling1411** [Calcium-Ion/new-api#514]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
负载均衡目前加权随机经常随到一个渠道，能否支持直接按权重顺序调用，不要随机

**Comment by fangyuan99** [comment]
同样，我想轮训的方式实现负载均衡，不知道能不能实现

**Comment by Atomesh** [comment]
我也有相同需求，因为像是 Github Model、Google AI Studio 都有多个账号负载均衡的需求，而如果出现了 429，就会直接切换到下一优先级的渠道，而如果将其设置不同的优先级，又会对一个 Key 造成过多请求，风险较高，因此希望能够有轮询的负载均衡方法，我检查了下文档、进行相关搜索，都没有发现相关设置，如果是我忽略了，麻烦提醒我一下设置的位置，非常感谢。

**Comment by 123hi123** [comment]
我也很好奇負載平衡的實現邏輯

**Comment by fangyuan99** [comment]
> 我也很好奇負載平衡的實現邏輯

目前就是加权平均，没得选

**Comment by 123hi123** [comment]
> > 我也很好奇負載平衡的實現邏輯
> 
> 
> 
> 目前就是加权平均，没得选

這名字讓我想到一位故佬友
原來是這樣
剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力

**Comment by proxyxai** [comment]
> 我也有相同需求，因为像是 Github Model、Google AI Studio 都有多个账号负载均衡的需求，而如果出现了 429，就会直接切换到下一优先级的渠道，而如果将其设置不同的优先级，又会对一个 Key 造成过多请求，风险较高，因此希望能够有轮询的负载均衡方法，我检查了下文档、进行相关搜索，都没有发现相关设置，如果是我忽略了，麻烦提醒我一下设置的位置，非常感谢。

proxyxai.com 早已支持

**Comment by fangyuan99** [comment]
> > > 我也很好奇負載平衡的實現邏輯
> > 
> > 
> > 目前就是加权平均，没得选
> 
> 這名字讓我想到一位故佬友 原來是這樣 剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力

L站的么？现在是加权随机，之前打错字了

**Comment by SericWong** [comment]
+1 优先级设置有用吗？可以先用高优的 高优挂了 再去选次优的 这样可以把一些渠道做兜底

**Comment by 123hi123** [comment]
> > > > 我也很好奇負載平衡的實現邏輯
> > > 
> > > 
> > > 目前就是加权平均，没得选
> > 
> > 
> > 這名字讓我想到一位故佬友 原來是這樣 剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力
> 
> L站的么？现在是加权随机，之前打错字了

確實是
![image](https://github.com/user-attachments/assets/6d3f0103-f7c5-4a3e-8c81-d14a5739543c)
這個頭像的老友 就不亂開盒在這裡了

**Comment by 123hi123** [comment]
> +1 优先级设置有用吗？可以先用高优的 高优挂了 再去选次优的 这样可以把一些渠道做兜底

有用 基本上就是從高等的先嘗試 然後一步步走向低等級

**Comment by 123hi123** [comment]
> > > > 我也很好奇負載平衡的實現邏輯
> 
> > > 
> 
> > > 
> 
> > > 目前就是加权平均，没得选
> 
> > 
> 
> > 這名字讓我想到一位故佬友 原來是這樣 剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力
> 
> 
> 
> L站的么？现在是加权随机，之前打错字了

好希望是加權平均 最近發現隨機有的時候還是隨機到固定幾個渠道

**Comment by fangyuan99** [comment]
> > > > > 我也很好奇負載平衡的實現邏輯
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 目前就是加权平均，没得选
> > 
> > 
> > > 
> > 
> > 
> > > 這名字讓我想到一位故佬友 原來是這樣 剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力
> > 
> > 
> > L站的么？现在是加权随机，之前打错字了
> 
> 好希望是加權平均 最近發現隨機有的時候還是隨機到固定幾個渠道

暂时用cherry studio可以支持

**Comment by 123hi123** [comment]
> > > > > > 我也很好奇負載平衡的實現邏輯
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 目前就是加权平均，没得选
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 這名字讓我想到一位故佬友 原來是這樣 剛發現一個更好的好像是叫動態加權 不過目前的做法也不錯 就是有點廢人力
> > > 
> > > 
> > > L站的么？现在是加权随机，之前打错字了
> > 
> > 好希望是加權平均 最近發現隨機有的時候還是隨機到固定幾個渠道
> 
> 暂时用cherry studio可以支持

但要重輸入渠道有點麻煩

**Comment by Calcium-Ion** [comment]
无计划，目前只会支持加权随机
