### ISSUE TITLE
设置 claude 系列模型的补全价格似乎不起作用

### ISSUE THREAD

**Issue by Evanora-y** [Calcium-Ion/new-api#515]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在设置里面倍率设置下，调整了【模型补全倍率（仅对自定义模型有效）】，发现claude模型倍率调整似乎不起作用，gpt的一些是正常的

**复现步骤**
在设置里面倍率设置下，调整了【模型补全倍率（仅对自定义模型有效）】，发现claude模型倍率调整似乎不起作用，gpt的一些是正常的

**预期结果**
不起作用

**Comment by Calcium-Ion** [comment]
仅对自定义模型有效，官方模型无法修改补全倍率
