### ISSUE TITLE
希望接入claude 接口 ，而不是一直使用claude接口出站

### ISSUE THREAD

**Issue by Evanora-y** [Calcium-Ion/new-api#516]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

本项目一直是OpenAI接口对外提供服务，但是OpenAI接口接用户反应，存请求格式的限制

存在该问题：

Chat Completion APImessages: roles must alternate between "user" and "assistant", but found multiple "user" roles ina row (request id:20240929200839927085502IUoyCGHc) (request id:20240929200839807541543Xtn8kXN7) (request id:20240929200839454414665IXAIN dT9)

**应用场景**

**Comment by QAbot-zh** [comment]
这不是 OpenAI 接口问题，是 claude api 本身的检测机制，即使换成 claude 接口，如果用户请求不符合user、assistant交替出现，也会报错的
