### ISSUE TITLE
直接使用playground时分组倍率是不生效的

### ISSUE THREAD

**Issue by yijia5478** [Calcium-Ion/new-api#517]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**
使用api时，分组倍率可以正常工作，但是直接使用playground时分组倍率是不生效的
**预期结果**

**相关截图**
如果没有的话，请删除此节。

https://oneperfect.cn/wp-content/uploads/2024/09/1727668576019.png

**Comment by Calcium-Ion** [comment]
实测没问题，更新一下最新版看看？
