### ISSUE TITLE
渠道分组和令牌分组删改后依旧按照原始数据调用问题

### ISSUE THREAD

**Issue by CJSen** [Calcium-Ion/new-api#520]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
      当前用户为svip分组，创建了两个令牌，一个令牌A分组选择svip（设置中已添加），一个令牌B选择默认分组。此时渠道中有两个渠道，一个glm（svip，default），一个gemini（svip）。当我使用令牌B调用gemini时，提示“当前分组 default 下对于模型 gemini-1.5-pro-latest 无可用渠道”，随后立即在gemini渠道中，添加分组default，即gemini（svip，default），此时再次使用令牌B调用依然显示无可用渠道。当我在令牌页面对令牌B做了一次分组更新（即修改为svip后，再修改为default），此时调用成功。
      反之，渠道从某个分组中删除后，原始创建的相关渠道令牌依然可以调用该渠道，直到令牌刷新。

**复现步骤**
如上

**预期结果**
修改了渠道的所属分组时，应该同步更新令牌分组相关信息，使其可调用或停用，

**Comment by Calcium-Ion** [comment]
更新渠道分组之后应该用一次修复数据库一致性，并不是令牌分组的问题
