### ISSUE TITLE
关于gemini模型读取pdf文件

### ISSUE THREAD

**Issue by gooldool** [Calcium-Ion/new-api#524]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gemini 在8月份更新以后，是支持转pdf文件为 base64 字符串的形式 来直接读取文件进行对话的，也就是跟image一样，不需要上传文件。但是现在image是可以正常对话的，换成pdf就不行了。
**复现步骤**

**预期结果**

**相关截图**
![2af9080bf4a988126243fa97ffc3fc1](https://github.com/user-attachments/assets/e178e586-ed37-4161-a422-7ec14044ac16)
![8d7136320c3b8f345b100f1c879d69d](https://github.com/user-attachments/assets/f84168de-c47a-4318-83be-665c2c8139cc)
![d228e543bee38acfe9d883d4d03073c](https://github.com/user-attachments/assets/44743235-1781-4de2-a657-a4985aecb1e9)
![image](https://github.com/user-attachments/assets/165233b4-e1e4-4be5-84f2-acbbdead448e)

**Comment by SericWong** [comment]
+1 希望支持

**Comment by SericWong** [comment]
顺便问下，claude和gpt支持传入文件吗

**Comment by Calcium-Ion** [comment]
已支持
