### ISSUE TITLE
从 oneapi 迁移后，后台登录后，部分请求 401，无法正常使用

### ISSUE THREAD

**Issue by zion-c** [Calcium-Ion/new-api#526]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
 使用了 oneapi 的数据库 （postgre），可以正常登录，但是部分请求（如 api/models api/groups）报错 401
**复现步骤**

**预期结果**
正常使用全部功能
**相关截图**
![image](https://github.com/user-attachments/assets/6446173f-864d-49fc-9ac8-71f6a531ddbd)
![image](https://github.com/user-attachments/assets/342f4a4c-a74f-4ebc-9a82-03a04788727c)

**Comment by ForgetAll** [comment]
我碰到了类似的问题，请问您的问题是怎么解决的呢？

**Comment by ForgetAll** [comment]
我的问题解决了，是因为本地运行，session 的存储配置有点问题
