### ISSUE TITLE
gpt-4o-mini-2024-07-18 这个模型二次请求无返回结果

### ISSUE THREAD

**Issue by uuu555552** [Calcium-Ion/new-api#532]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请求gpt-4o-mini-2024-07-18 这个模型，第一次可以正常请求，然后第二次不返回任何结果，直到超时。通过官方直连访问，没有什么错误，可以正常返回结果。
**复现步骤**
api请求示例
{
  "model": "gpt-4o-mini-2024-07-18",
  "messages": [
    {
      "role": "system",
      "content": "You are a Human Resource expert tasked with extracting specific fields from a job description. Please provide the output in a JSON format. Here are the fields you need to extract and the guidance to follow:\n\ntitle:\n- Extract a clean string of the job title from the job postings.\n- Exclude any unrelated information such as salary, urgency, or location.\n- Retain only the seniority, job title, and job domain. For example: \"Senior Backend Software Engineer\", \"Software Engineer - New College Grad\", \"Product Manager in Saas\", etc.\n\nsummary:\n- A succinct summary of the job description in 2-3 sentences.\n- If the given job description includes the company's introduction, please output one sentence about the company's introduction followed by 1~2 sentences about the job's introduction. If the job description does not include the company, then return only 1~2 sentences about the job.\n- Please replace the company name in summary with the given company name.\n\neducation_requirements:\n- Please extract the required formal education degrees or certifications that are explicitly mentioned in the given JOB DESCRIPTION.\n- Focus only on educational degrees such as \"Bachelor's Degree in Computer Science\", \"Master's Degree in Business Administration\", etc.\n- Do not include years of work experience or specific framework knowledge in this section.\n- If the educational requirements are not mentioned, an empty array is returned.\n\nresponsibilities:\n- Extract all the responsibilities of the position from the given job description.\n- Just copy the responsibilities, do not make any changes.\n- Just include the responsibilities and do not include anything else, such as qualifications.\n\nwork_model:\n- Extract the work model from the given job title and job description, and please return one of the following three options: \"ON_SITE\", \"HYBRID\", \"REMOTE\"\n  -- ON_SITE: Employees work full-time from a physical office location. This model requires employees to be present at the office during standard working hours.\n  -- HYBRID: Employees split their time between working remotely and working from a physical office.\n  -- REMOTE: Employees work exclusively outside the traditional office, often explicitly referred to as \"remote\" in the job description.\n- If the work model is not mentioned, an empty string is returned.\n- The extracted work model must have an explicit counterpart in the original text.\n\nlocation\n- Extraction of duty stations explicitly mentioned in given job title and job description.\n- The location of the work must be the exact geographical location of the United States, the format should be adjusted to \"City, State Abbreviation\" format, if the work location is not the United States or no clear geographical location, please return empty string.\n- The extracted location must have an explicit counterpart in the original text.\n\n[Sample output structure]:\n{\n  \"title\": \"...\",\n  \"summary\": \"...\",\n  \"education_requirements\": [\"...\"],\n  \"responsibilities\": [\"...\"],\n  \"work_model\": \"...\",\n  \"location\": \"...\"\n}\n"
    },
    {
      "role": "user",
      "content": "Job title: Software Development Engineer, Amazon Aurora Storage\nCompany name: Mercury\nCompany intro: Mercury offers FDIC-insured accounts, virtual & physical debit cards, currency exchange, domestic, and international wires.\nJob Description: \nRole: Sales Rep Biz Development\n\nLocation: Albany, NY\n\nResponsibilities:\n\nPerform cost-benefit and needs analysis of existing/potential customers to meet their needs\nEstablish, develop and maintain positive business and customer relationships\nNetwork with customers to identify new opportunities\nExpedite the resolution of customer issues to maximize satisfaction\nAchieve agreed upon sales targets and outcomes within schedule\nCoordinate sales effort with team members and other departments\nProvide management with reports on customer needs and interests, competitive activities, and potential for new products and services.\nResearch on upcoming projects in the region or wherever the Regional clients are specifying\nKeep abreast of best practices and promotional trends\nContinuously improve through feedback\nRequirements\nProven track record and experience as a field sales representative\nFamiliarity with using a CRM to report and track activity and results\nAbility to build productive and professional business relationships\nHighly motivated and target driven\nExcellent selling, communication and negotiation skills\nPrioritizing, time management and organizational skills\nRelationship management skills and openness to feedback\nOutput:"
    }
  ],
  "temperature": 0.1,
  "response_format": {
    "type": "json_schema",
    "json_schema": {
      "name": "basic_tools_response",
      "strict": true,
      "schema": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "domains": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "seniority": {
            "type": "string"
          },
          "summary": {
            "type": "string"
          },
          "education_requirements": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "responsibilities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["title", "domains", "seniority", "summary", "education_requirements", "responsibilities"],
        "additionalProperties": false
      }
    }
  }
}

**预期结果**
{
	"id": "chatcmpl-AID7GA4XLYIuT53o2ROVWAds1ixvH",
	"object": "chat.completion",
	"created": 1728903686,
	"model": "gpt-4o-mini-2024-07-18",
	"choices": [
		{
			"index": 0,
			"message": {
				"role": "assistant",
				"content": "{\n  \"title\": \"Sales Representative - Business Development\",\n  \"domains\": [],\n  \"seniority\": \"\",\n  \"summary\": \"Mercury offers FDIC-insured accounts, virtual & physical debit cards, currency exchange, domestic, and international wires. The Sales Representative in Business Development will perform cost-benefit analyses, establish and maintain customer relationships, and achieve sales targets.\",\n  \"education_requirements\": [],\n  \"responsibilities\": [\n    \"Perform cost-benefit and needs analysis of existing/potential customers to meet their needs\",\n    \"Establish, develop and maintain positive business and customer relationships\",\n    \"Network with customers to identify new opportunities\",\n    \"Expedite the resolution of customer issues to maximize satisfaction\",\n    \"Achieve agreed upon sales targets and outcomes within schedule\",\n    \"Coordinate sales effort with team members and other departments\",\n    \"Provide management with reports on customer needs and interests, competitive activities, and potential for new products and services.\",\n    \"Research on upcoming projects in the region or wherever the Regional clients are specifying\",\n    \"Keep abreast of best practices and promotional trends\",\n    \"Continuously improve through feedback\"\n  ]\n}",
				"refusal": null
			},
			"logprobs": null,
			"finish_reason": "stop"
		}
	],
	"usage": {
		"prompt_tokens": 950,
		"completion_tokens": 235,
		"total_tokens": 1185,
		"prompt_tokens_details": {
			"cached_tokens": 0
		},
		"completion_tokens_details": {
			"reasoning_tokens": 0
		}
	},
	"system_fingerprint": "fp_e2bde53e6e"
}
**相关截图**
![1728904274814](https://github.com/user-attachments/assets/168ce1cb-2d4f-40ce-9b40-60b469e613c4)    官方正常返回结果。
![1728904503652](https://github.com/user-attachments/assets/b912ea3c-2f86-493e-ad8a-82266d58d497)   走new-api 请求无返回结果，同时docker日志报错relay error (channel #967, status code: 500): write tcp 172.17.0.6:3000->36.44.167.2:7126: write: broken pipe

如果没有的话，请删除此节。

**Comment by GetGoAPI** [comment]
已经部分排查，和这个参数有关系。response_format，带这个参数有问题，不带这个参数就没有问题，官方是支持response_format参数的。
