### ISSUE TITLE
关于系统api无法完成post请求的问题

### ISSUE THREAD

**Issue by sunsky89757** [Calcium-Ion/new-api#541]
![image](https://github.com/user-attachments/assets/b636500d-214c-466f-a6e4-4f83afff4aa3)

您好，one-api中的系统api，post请求需要怎么改？我用one-api的post  /api/topup 在new-api中无法实现。one-api中测试可正常post。

参考阅读：https://github.com/songquanpeng/one-api/blob/main/docs/API.md#api-%E5%88%97%E8%A1%A8

**Comment by 123hi123** [comment]
不太確定
不過這裡是new api 不是one api 可以把這裡關了去one api問

**Comment by Calcium-Ion** [comment]
不支持该操作
