### ISSUE TITLE
github models o1-mini 与 o1preview 无法调用成功

### ISSUE THREAD

**Issue by chaos-zhu** [Calcium-Ion/new-api#543]
除了 o1-mini与o1-preview ，其他模型接入都正常

![image](https://github.com/user-attachments/assets/aa6ff92b-f8eb-492d-86d2-82e48503e1b1)

**Comment by QAbot-zh** [comment]
首先不是应该检查一下是否有相应的权限吗

**Comment by 123hi123** [comment]
> 首先不是应该检查一下是否有相应的权限吗

說的對
