### ISSUE TITLE
增加数学公式的优化

### ISSUE THREAD

**Issue by sw9960** [Calcium-Ion/new-api#545]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
增加数学公式的优化显示
**应用场景**
数学公式

**Comment by Calcium-Ion** [comment]
这和new api有什么关系吗

**Comment by sw9960** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 123hi123** [comment]
> 这和new api有什么关系吗

可能他會用latex來命名他的模型

**Comment by somnifex** [comment]
> > 这和new api有什么关系吗
> 
> 可能他會用latex來命名他的模型

那这也是前端要做的工作啊

**Comment by sw9960** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
