### ISSUE TITLE
mistral 模型接口使用报错

### ISSUE THREAD

**Issue by xinlimei** [Calcium-Ion/new-api#546]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我当前使用的版本是v0.3.0.0，在添加mistal模型后，在渠道那里测试，是通过的
![image](https://github.com/user-attachments/assets/aeeb7d05-c4b5-4e4f-b153-6b5466a818ca)
但是在playground那里测试，就失败了
![image](https://github.com/user-attachments/assets/e0cf134d-08c6-42b2-a138-d4ebf6e85550)
而且在chatgpt-next-web等项目中也无法使用。

我发现one-api中已经兼容了mistral模型，并且在渠道的类型中选择openai也是可以的。不知道为什么在new-api把mistral中去掉了。
**复现步骤**

**预期结果**
我希望可以在new-api可以正常使用mistral的模型，谢谢

**Comment by Calcium-Ion** [comment]
需要您提供测试密钥

**Comment by xinlimei** [comment]
mistral 密钥：16GP8x2eHjXdjQUwjTlcdbKZqPxJLukR



***@***.***
 
发件人： Calcium-Ion
发送时间： 2024-11-05 16:20
收件人： Calcium-Ion/new-api
抄送： xinlimei; Author
主题： Re: [Calcium-Ion/new-api] mistral 模型接口使用报错 (Issue #546)
需要您提供测试密钥
