### ISSUE TITLE
绘图失败不返还金额

### ISSUE THREAD

**Issue by longkun0203** [Calcium-Ion/new-api#55]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
更新0.1.2，绘图失败不返还金额

**Comment by Calcium-Ion** [comment]
请提供日志或者复现方法

**Comment by longkun0203** [comment]
> 请提供日志或者复现方法

网站日志吗？，复现方法就是绘画失败后台，系统不会自动返还用户金额
![image](https://github.com/Calcium-Ion/new-api/assets/55705293/c86a8a18-1d60-4715-8480-5bf77eb130f1)
danshi但实际上我的上家平台是有给我返还的，我这边不能返还我的平台用户

**Comment by longkun0203** [comment]
几百次失败了，后台没有一条关于失败返款的，只有一条邀请奖励
![image](https://github.com/Calcium-Ion/new-api/assets/55705293/2b65d31e-b843-495e-916c-f270d0e37912)

**Comment by longkun0203** [comment]
> 请提供日志或者复现方法

![image](https://github.com/Calcium-Ion/new-api/assets/55705293/e2fefcbf-b3ad-466f-8001-8c0940a36439)

**Comment by longkun0203** [comment]
> 请提供日志或者复现方法

![image](https://github.com/Calcium-Ion/new-api/assets/55705293/385bef83-1233-408b-a8d8-4df749ed7be1)

**Comment by Calcium-Ion** [comment]
感谢反馈，后面会集中处理mj的问题

**Comment by longkun0203** [comment]
> 感谢反馈，后面会集中处理mj的问题

感谢
