### ISSUE TITLE
realtime 实际扣费与日志花费有大bug

### ISSUE THREAD

**Issue by ArcaneWhispers** [Calcium-Ion/new-api#554]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

两个问题：

一、在某些情况实际扣费与日志显示的扣费出入很大。
二、限额的令牌会无限扣费 直至账户余额扣完。

**复现步骤**

## 问题一：

账户余额1刀
令牌余额1刀

1. realtime聊一会，由于预扣费不足自动断开
2. 此时账户和令牌余额都只剩余$0.38左右（实际消费$0.62）
3. 查看日志显示花费 $2.335376,出入比较大

## 问题二：

当令牌设置了限额，只要账户有余额 就可以一直聊，直到账号余额耗尽。有时候会分配令牌给其他人使用，有些中转商会售卖令牌额度，这种情况就会造成极大的损失。

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by iszcz** [comment]
看到个内置的realtime补全是10，正确的补全应该是2，多计费5倍了

**Comment by Calcium-Ion** [comment]
不支持分发令牌，造成损失后果自负
