### ISSUE TITLE
bad_response_status_code

### ISSUE THREAD

**Issue by chrisyuuuuu** [Calcium-Ion/new-api#556]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
{"message":"","type":"upstream_error","param":"524","code":"bad_response_status_code"}
**复现步骤**
不能复现，不知道为什么会出现这个问题
**预期结果**
不报这个错
**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
cloudflare请求超过100秒会报524
