### ISSUE TITLE
用的逆向gpt-4o-all的api,我后台如何配置别人的接口和令牌，可以上传文件并分析，如果用了我自己的newapi接口，上传文件的时候会报这个错误

### ISSUE THREAD

**Issue by wujunya** [Calcium-Ion/new-api#557]
用的逆向gpt-4o-all的api,我后台如何配置别人的接口和令牌，可以上传文件并分析，如果用了我自己的newapi接口，上传文件的时候会报这个错误

{
  "error": {
    "message": "fail to decode image config(webp): riff: missing RIFF chunk header (request id: 20241107123024595323162Rc9QKBXB)",
    "type": "new_api_error",
    "param": "",
    "code": "count_token_messages_failed"
  }
}

**Comment by Calcium-Ion** [comment]
设置环境变量GET_MEDIA_TOKEN为false

**Comment by wujunya** [comment]
![image](https://github.com/user-attachments/assets/8563d04f-c6eb-434e-8105-dd1b070921f8)
![image](https://github.com/user-attachments/assets/905f20e9-86ed-456a-a7be-d7a61718137c)
![image](https://github.com/user-attachments/assets/8a0b3d09-7775-4b68-a290-4b8650097396)


GPTs逆向模型报错，是因为什么呢？渠道都配置好了，依然报错
