### ISSUE TITLE
缺失基础模型倍率

### ISSUE THREAD

**Issue by FF0E** [Calcium-Ion/new-api#558]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

似乎有很多基础模型没有被包含在倍率文件中, 尝试重置发现无效, 来 repo 搜索才发现代码中未计算. (只在 `model-ratio.go` 找到了相关计算)

例如 `gemini-1.5-pro` 标价便是 60/240, 虽然 `gemini-1.5-pro-latest` 是正常的, 但是没有这些基础模型的.

看了下 One API 文件中是包含了这些的. 请问是没有来得及更新还是设计使然, 因为看到确实似乎没有添加很多基础模型的倍率, 是需要在其他地方修改吗.

**Comment by QAbot-zh** [comment]
因为非标模型默认倍率是30倍，自行添加到设置里吧

**Comment by FF0E** [comment]
>  因为非标模型默认倍率是30倍，自行添加到设置里吧

因为比如我上面给的例子, 也都是官方的模型, 看到缺失才来问下. 我自己参照着 oneapi 的已经加过了, 谢谢提醒.
