### ISSUE TITLE
令牌修改接口，后端未做校验，直接请求令牌修改接口，可以将令牌分组改为任意分组

### ISSUE THREAD

**Issue by yinqf** [Calcium-Ion/new-api#559]
下面是请求信息，希望在接口里面做下校验，如果用户没有此分组的权限，接口请求的时候，拦截并返回错误
![QQ_1730969205466](https://github.com/user-attachments/assets/7fcbe477-6682-477c-a1f8-a9f99eea35c8)

**Comment by Calcium-Ion** [comment]
你当然是可以任意修改这个分组，但是调用的时候无法调用

**Comment by yinqf** [comment]
的确是不能请求，已经修复了
