### ISSUE TITLE
GPTs逆向模型报错，是因为什么呢？渠道都配置好了，依然报错

### ISSUE THREAD

**Issue by wujunya** [Calcium-Ion/new-api#561]
![image](https://github.com/user-attachments/assets/70c5d7ce-7138-49d1-84bc-d94aed42b59f)
![image](https://github.com/user-attachments/assets/323eb6ba-4fa6-49ea-8f9a-aafea9726c21)
![image](https://github.com/user-attachments/assets/aa384715-0b78-407d-99f4-bc6641641870)

**Comment by Calcium-Ion** [comment]
模型列表加入gpt-4-gizmo-*
