### ISSUE TITLE
数据库保存所有请求日志吗？怎么清除啊 时间长了数据库会爆吧

### ISSUE THREAD

**Issue by SericWong** [Calcium-Ion/new-api#565]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
这种问题，你去问ai都比在这问得到答案快

**Comment by SericWong** [comment]
> 这种问题，你去问ai都比在这问得到答案快

在db里我知道怎么删除，我是想了解 系统是不是带这个设置，可以配置自动删除日志功能
