### ISSUE TITLE
增加用户组或用户/令牌限速

### ISSUE THREAD

**Issue by utopeadia** [Calcium-Ion/new-api#571]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
为用户组、用户、令牌或者细粒度权限增加速率限制
**应用场景**
多用户防止抢占资源

**Comment by somnifex** [comment]
特别是基于令牌的限制，不同用途对速度要求不太相同，有些客户端无脑请求会直接阻塞整个服务

**Comment by Calcium-Ion** [comment]
不会在开源版增加此功能
