### ISSUE TITLE
在使用grok-beta，选择为openai渠道时，会把finish_reason 的值给删掉，从而导致对接的openai库报错，可能是个严重问题

### ISSUE THREAD

**Issue by ahasasjeb** [Calcium-Ion/new-api#572]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
在使用grok-beta，选择为openai渠道时，会把finish_reason 的值给删掉，从而导致对接的openai node库报错，无法执行工具调用
**复现步骤**
添加使用x AI 的grok-beta，使用工具调用，使用 node openai库
**预期结果**
正确执行工具调用

 {
  id: "dd1638ec-3c40-49d3-9bc1-a81935b8fb14",
  object: "chat.completion.chunk",
  created: 1731922720,
  model: "grok-beta",
  usage: {
    prompt_tokens: 835,
    completion_tokens: 8,
    total_tokens: 843,
  },
  system_fingerprint: "fp_be475d80cf",
  choices: [
    {
      finish_reason: undefined,  <----这里，实测x api 接口是正常的
      index: 0,
      message: {
        role: "assistant",
        content: "我正在获取上海的天气信息。",
      },
      logprobs: null,
    }
  ],
}

**Comment by 123hi123** [comment]
這裡變成undefined 確實難受

**Comment by Calcium-Ion** [comment]
请更新到最新版本
