### ISSUE TITLE
AWS Bedrock的claude-3-5-sonnet-20241022模型配置后无法使用。

### ISSUE THREAD

**Issue by ZefanHu** [Calcium-Ion/new-api#577]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
错误：InvokeModel: operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: 8fc56c06-b6ee-49b4-b642-12e902f08eca, ValidationException: Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.

**复现步骤**
![image](https://github.com/user-attachments/assets/aced6e88-b198-4741-845e-fdd98e0e9599)

**预期结果**
点击测试按钮，返回通过测试消息。这个模型不支持按需调用，claude-3-5-sonnet-20240620就是正常的。

**Comment by ZefanHu** [comment]
切换一个地区就行，有些地区newapi不支持

**Comment by Calcium-Ion** [comment]
并不是new-api不支持，而是你这个模型在某个地区不支持

**Comment by ZefanHu** [comment]
> 并不是new-api不支持，而是你这个模型在某个地区不支持

us-east-1这个地区，看说明不能直接用，需要传inference配置文件，us-west-2不需要这个文件，可以直接用newapi

**Comment by Calcium-Ion** [comment]
new-api支持跨区调用，直接填写完整模型名称

**Comment by ZefanHu** [comment]
> new-api支持跨区调用，直接填写完整模型名称

了解，也就是us-east-1不能像us-west-2那样，填写好ak|sk|region，一键填入相关模型比如claude-3-5-sonnet-20241022直接用。需要传aws的model id比如us.anthropic.claude-3-5-sonnet-20241022-v2:0使用嘛。不太了解，我目前的情况是，完全一样的配置，us-west-2可以用，us-east-1不能用，但是两个地区我都有权限可以在aws官网使用。

**Comment by ZefanHu** [comment]
> new-api支持跨区调用，直接填写完整模型名称

试了一下，not work，我简单分享一下我遇到的报错，感兴趣可以看看，我确定是us-east-1用不了claude-3-5-sonnet-20241022，但是claude-3-5-sonnet-20240620可以用，us-west-2全部可以使用。两个地区我对cluade的权限应该是一样的。
newapi报错是下面这样的：
错误：InvokeModel: operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: c608955d-274d-4d96-b0ab-523b0b051b37, ValidationException: Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.
实际上我应该允许了这个地区所有的模型的访问：
"Resource": "arn:aws:bedrock:us-east-1::foundation-model/*"
我不是aws的专业人员，但是这两个地区的claude-3-5-sonnet-20241022，直观的能看到有一点区别：
us-east-1多了一个提示This model can only be used through an inference profile.
us-west-2没有这个提示

**Comment by Calcium-Ion** [comment]
你说无法调用我也没有办法，只能说new是支持这样做的，例如完整的模型名称是us.anthropic.claude-3-5-sonnet-20241022-v2:0

**Comment by sunerpy** [comment]
> > new-api支持跨区调用，直接填写完整模型名称
> 
> 试了一下，not work，我简单分享一下我遇到的报错，感兴趣可以看看，我确定是us-east-1用不了claude-3-5-sonnet-20241022，但是claude-3-5-sonnet-20240620可以用，us-west-2全部可以使用。两个地区我对cluade的权限应该是一样的。 newapi报错是下面这样的： 错误：InvokeModel: operation error Bedrock Runtime: InvokeModel, https response error StatusCode: 400, RequestID: c608955d-274d-4d96-b0ab-523b0b051b37, ValidationException: Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model. 实际上我应该允许了这个地区所有的模型的访问： "Resource": "arn:aws:bedrock:us-east-1::foundation-model/*" 我不是aws的专业人员，但是这两个地区的claude-3-5-sonnet-20241022，直观的能看到有一点区别： us-east-1多了一个提示This model can only be used through an inference profile. us-west-2没有这个提示

跨区域推理需要使用profile id而不是model id
