### ISSUE TITLE
Lobo Chat Anthropic 请求的是 /v1/messages 但是new-api 是/v1/completions 并没有messages接口

### ISSUE THREAD

**Issue by xiaoyi510** [Calcium-Ion/new-api#578]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x  ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Lobo Chat Anthropic 请求的是 /v1/messages 但是new-api 是/v1/completions 并没有messages接口
**复现步骤**

**预期结果**
支持 LoboChat 的 Anthropic
**相关截图**
![image](https://github.com/user-attachments/assets/6ef9278d-805a-435e-8694-c5c231ba0bd0)

**Comment by 1PercentSync** [comment]
![image](https://github.com/user-attachments/assets/28dee2a2-a796-4052-9320-1cf587f4b78f)

/v1/messages并非openai格式接口

**Comment by QAbot-zh** [comment]
所以你可以在 OpenAI 类型里调用 claude

**Comment by xiaoyi510** [comment]
额 可是 我看readme是支持 claude 啊

**Comment by QAbot-zh** [comment]
> 额 可是 我看readme是支持 claude 啊

支持 （使用 OpenAI 格式调用）claude 模型 啊

**Comment by Calcium-Ion** [comment]
你可以使用new-api-horizon，支持/v1/messages（claude格式）

**Comment by Calcium-Ion** [comment]
你图里面使用的是Claude格式，这个项目只支持OpenAI格式调用Claude

**Comment by daggeryu** [comment]
location /v1/messages {
          rewrite ^/v1/messages(.*)$ /v1/chat/completions$1 break;
          proxy_set_header Authorization $http_x_api_key;
          client_max_body_size  64m;
          proxy_http_version 1.1;
          proxy_pass http://127.0.0.1:3001;  # 请根据实际情况修改你的端口
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_cache_bypass $http_upgrade;
          proxy_set_header Accept-Encoding gzip;
          proxy_read_timeout 300s;  # GPT-4 需要较长的超时时间，请自行调整  
    } nginx这样配置，可能可以解决你的问题

**Comment by xiaoyi510** [comment]
使用openai 替换模型 倒是能解决 
但是希望能加入 claude 官方接口方式
有些途径不支持选择OpenAi支持什么模型

**Comment by Calcium-Ion** [comment]
> 你可以使用new-api-horizon，支持/v1/messages（claude格式）
