### ISSUE TITLE
为谷歌对话模型增加safety settings配置

### ISSUE THREAD

**Issue by fl0w1nd** [Calcium-Ion/new-api#581]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
谷歌支持safety settings安全过滤的参数，希望增加
https://ai.google.dev/gemini-api/docs/get-started/tutorial?lang=swift&hl=zh-cn#use-safety-settings
**应用场景**

**Comment by Calcium-Ion** [comment]
请参考one api项目设置GEMINI_SAFETY_SETTING环境变量
