### ISSUE TITLE
无法使用邮箱验证注册，收不到验证码

### ISSUE THREAD

**Issue by harrisonhxy** [Calcium-Ion/new-api#583]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
我的初衷是使用自己的域名邮箱（申请的是阿里云的企业邮箱），进行注册验证，但是在点发送验证码后，按钮就变灰色了，并且没有收到邮件，也没有邮件发出。没有访问凭证，是不是无法使用域名邮箱？

起初以为是域名邮箱的问题，但是我在更换qq邮箱后，并填写smtp访问凭证后，发现依然无法收发验证码。依然是在点发送验证码后，按钮就变灰色。没有邮件收发

qq邮箱的smtp服务区地址：smtp.qq.com
qq邮箱的smtp端口：465
qq邮箱的smtp账户：2010xxxxxx@qq.com（我的qq邮箱）
qq邮箱的smtp发送者邮箱：2010xxxxxx@qq.com（我的qq邮箱）
qq邮箱的smtp访问凭证：bjbkxxxxxxxxxxxxx（我在qq邮箱获取的授权码）

**预期结果**
能使用邮箱注册验证

**相关截图**
newapi配置
![image](https://github.com/user-attachments/assets/113412ff-9082-42f5-9b7e-66d138814337)
![image](https://github.com/user-attachments/assets/3cab6818-129d-4ff8-9188-0388afb6696f)
1panel newapi容器运行正常，我也开放了465端口
![image](https://github.com/user-attachments/assets/3a05fc51-e44a-46cf-932a-b6e3386ed76c)
此处获取的qq邮箱授权码
![image](https://github.com/user-attachments/assets/adf02d57-5bd7-454a-8121-d14587cd508d)

**Comment by Rebellce** [comment]
有可能是你的服务器就ban了邮件服务了吧？我开始的服务器就发不了邮件，后面换了一台vps就可以了。

可以在这里测试是不是凭证的问题：
> https://www.gmass.co/smtp-test

如果是linux可以跑一下融合怪的脚本看看是不是自己ip的问题，跑第4个单项测试的第4个就可以， 看看邮件服务是不是可用：
> curl -L https://github.com/spiritLHLS/ecs/raw/main/ecs.sh -o ecs.sh && chmod +x ecs.sh && bash ecs.sh`

因为我也遇到过类似的问题希望可以帮到你~

**Comment by harrisonhxy** [comment]
感谢您的帮助，确实是我的VPS禁止了465和25端口，我现在改用587可以实现该功能了
