### ISSUE TITLE
支持 OpenRouter 的模型

### ISSUE THREAD

**Issue by jtsang4** [Calcium-Ion/new-api#601]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
支持 [OpenRouter](https://openrouter.ai/) 的模型，现在调用会报错：`错误：invalid character '<' looking for beginning of value`

**应用场景**
OpenRouter 的模型名称类似 `google/gemini-flash-1.5-8b-exp`，不知道和这个有没有关系。

**Comment by Calcium-Ion** [comment]
是你自己填错代理地址，OpenRouter不需要new兼容

**Comment by jtsang4** [comment]
我的代理地址填的是这个 https://openrouter.ai ，应该没有错，直接 curl 也能正确返回。我再调试下看看

**Comment by jtsang4** [comment]
感谢。确实是我的代理地址配错了，应该配置 https://openrouter.ai/api ，和其它的代理源不太一样

**Comment by night2049** [comment]
老哥请教一下你详细是怎么配置的吗，我按你这个流程配置了，点测试一直显示405
