### ISSUE TITLE
建议增加对于gemini-exp-1206支持

### ISSUE THREAD

**Issue by taiyi747** [Calcium-Ion/new-api#606]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
gemini-exp-1206现在是lmarena和livebench双排行榜第一，是目前免费调用的模型里最好的模型
**应用场景**
文本生成，图片识别

**Comment by Calcium-Ion** [comment]
直接添加自定义模型gemini-exp-1206就行了，我没有这么多精力去频繁更新模型名称

**Comment by scu-lixiao** [comment]
日志中为何不能显示Gemini？

**Comment by Calcium-Ion** [comment]
> 日志中为何不能显示Gemini？

不知道你说的是什么问题
