### ISSUE TITLE
希望增加用户组请求频率限制功能

### ISSUE THREAD

**Issue by bestZwei** [Calcium-Ion/new-api#608]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

希望增加对单个用户以及用户组的请求频率限制功能

有人提过类似的issue，好像没有后续了https://github.com/Calcium-Ion/new-api/issues/441 https://github.com/Calcium-Ion/new-api/issues/571

**应用场景**

**Comment by Calcium-Ion** [comment]
开源版无计划

**Comment by tbphp** [comment]
@Calcium-Ion 不能对单独用户进行限制，使用起来确实不方便。和别人共有，但是又希望vip组能更高的频次。
开源版无计划。
是无开发计划吗，是否接受PR呢？
