### ISSUE TITLE
在渠道内增加一个强制格式化输出的选项

### ISSUE THREAD

**Issue by billzhen870** [Calcium-Ion/new-api#620]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
在渠道内增加一个强制格式化输出的选项。

**应用场景**
某些项目转发后构造的响应不一定能被一些项目识别，强制格式化处理为new-api通常使用的格式能避免很多问题。

**Comment by Calcium-Ion** [comment]
目前在自定义渠道下支持设置force_format
