### ISSUE TITLE
dify 请求不要输出workflow各个节点的日志

### ISSUE THREAD

**Issue by tianzecn** [Calcium-Ion/new-api#627]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

Workflow: d9de6782-042b-4252-8340-4c4ed8cd5b45
Node: 1733221122761
Node: 1734332077857
{"imgurl": "[https://cdn.discordapp.com/attachments/ Node): 1734332094030

如果dify的聊天助手是工作流编排，会输出workflow各个节点的日志，希望流式传输时能丢弃开始与结尾时的节点日志，只保留event值为message的

**应用场景**

**Comment by Calcium-Ion** [comment]
请你仔细阅读Readme
