### ISSUE TITLE
调用Gemini 2.0 Flash Thinking Exp返回错误

### ISSUE THREAD

**Issue by markintouch** [Calcium-Ion/new-api#639]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
已升级到最新v0.4.0.1。调用Gemini 2.0 Flash Thinking Exp返回错误no candidates returned

**Comment by JustDoIt166** [comment]
渠道类型使用google gemini，我正常使用
![Screenshot_2024-12-20-09-50-59-88_32cba261fc08a501ce70de75bdbe2575](https://github.com/user-attachments/assets/e8705ed7-14e3-44d9-8ab3-1ced7bf63983)

**Comment by QAbot-zh** [comment]
连通性错误不影响实际调用使用

**Comment by haso2007** [comment]
学到了，感谢各位老大。还以前连通不行就不能用呢
