### ISSUE TITLE
请求优化手机端ui

### ISSUE THREAD

**Issue by 2693551060** [Calcium-Ion/new-api#64]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
把手机端UI优化一下，求求拉
**应用场景**
手机用户

**Comment by Calcium-Ion** [comment]
工作量较大。你有需要优先优化的地方吗
