### ISSUE TITLE
希望能同步官方彩虹易支付最新虚拟币支付

### ISSUE THREAD

**Issue by ChangeYu0229** [Calcium-Ion/new-api#644]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
商户号(pid) 固定填写：1000
商户密钥(key) 同AUTH_TOKEN
支付类型(type) 可选值：usdt.trc20和tron.trx 两种支付方式
注意事项：大部分商户系统的支付类型都是wxpay或者alipay，这里需要各方系统自行进行适配。
**应用场景**
目前的易支付使用插件无法兼容到其他币种的付款方式

**Comment by Calcium-Ion** [comment]
请使用new-api-horizon https://github.com/Calcium-Ion/new-api-horizon

**Comment by Calcium-Ion** [comment]
开源版为个人/内部用户专用，请勿再提此类issue
