### ISSUE TITLE
0.4.1.4版本更新后vip分组会在用户编辑的分组消失，需要在运营重新删掉再设置，并且点击定价会提示record not found

### ISSUE THREAD

**Issue by buwanyuanshen** [Calcium-Ion/new-api#659]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
请提供您的操作+报错的截图

**Comment by buwanyuanshen** [comment]
![image](https://github.com/user-attachments/assets/8134addb-1175-47e8-b1d2-937c343d16bf)

**Comment by buwanyuanshen** [comment]
也许是特例，我两个网站，一个有问题，另一个没问题

**Comment by Calcium-Ion** [comment]
是点击价格页面就出现record not found吗

**Comment by buwanyuanshen** [comment]
> 是点击价格页面就出现record not found吗

嗯
