### ISSUE TITLE
模型管理页面分页问题

### ISSUE THREAD

**Issue by iLayPark** [Calcium-Ion/new-api#66]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
总共有11个模型
每页10条，当打开第二页的时候，显示总共三页
每页20条，显示总共2页
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
感谢反馈，后期会修复
