### ISSUE TITLE
能否增加像Open webui那样根据接口地址自动识别模型

### ISSUE THREAD

**Issue by glaw1984** [Calcium-Ion/new-api#664]
Open webui可以根据接口地址自动识别能够使用的模型，避免了手动更新和增加参数的麻烦，以后官方更新了只要在渠道输入地址和密钥即可自动更新模型名称

**Comment by Calcium-Ion** [comment]
![image](https://github.com/user-attachments/assets/5a3edc9d-15af-44e2-89c5-cf15dbf970e0)
