### ISSUE TITLE
返回空值，不会报错

### ISSUE THREAD

**Issue by SericWong** [Calcium-Ion/new-api#666]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
返回空值，不会切换渠道，希望返回空 可以自动切换渠道重试
**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by kujilao** [comment]
渠道检测只要返回200状态码就是有效渠道，严格检测模式可能wip版本做了

**Comment by Calcium-Ion** [comment]
不会支持空补全重试功能
