### ISSUE TITLE
额度用尽后无明确提示，是用户额度、渠道额度还是令牌额度

### ISSUE THREAD

**Issue by sagezhj** [Calcium-Ion/new-api#667]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
超管用户，使用一段时间后会无法使用，所有渠道、所有令牌都正常。

**复现步骤**
1. Docker服务搭建
2. 添加渠道
3. 添加令牌，并设定为不限时间、无限额度
4. 使用一段时间后，所有渠道、令牌都无法使用，查看Docker日志提示：chat pre-consumed quota failed, user quota: 13810, need quota: 15000

**预期结果**
1. 创建用户的时候，没有提示额度限制。希望在创建用户时，可以提示设置额度。
2. 用户额度使用完成后，没有提示。希望在日志中可以体现因那项额度用完报错提示，因为额度总共有三处限制，一处用户额度、一处渠道额度、一处令牌额度。
3. 超级管理员用户有默认额度，但无提示，且无法设置为无限额度。对于仅使用本地接口的用户来说，可以允许超管设置无限额度。所以建议增加超管额度无限设置，比如设置成-1。

**Comment by Calcium-Ion** [comment]
难道chat pre-consumed quota failed, user quota: 13810, need quota: 15000还提示的不够清楚吗？user quota: 13810, need quota: 15000

为了安全考虑，更不可能允许用户无限额度，包括管理员，请按照系统设计来！

**Comment by scu-lixiao** [comment]
最近也碰到了这个问题，额度用完了（以前确实是设置了无限额度），所有模型的剩余额度都为0，不可用。现在怎么修改都无用，剩余额度始终显示为0。
![IMG_0535](https://github.com/user-attachments/assets/312db85c-7fd3-4c60-b346-b0334810d0d5)
![IMG_0536](https://github.com/user-attachments/assets/036a0aa8-a3b5-4ec9-937e-2b858d292b40)

**Comment by chenjiawei30** [comment]
一样的问题，剩余额度都是0，请问如何解决

**Comment by chenjiawei30** [comment]
![Image](https://github.com/user-attachments/assets/3f79986a-3062-4f02-8ca5-2686463df3c4)

**Comment by sagezhj** [comment]
这个应用里有3个额度，除了常用的**渠道额度**和**令牌额度**，还有**用户额度**，需要在用户管理里，增加管理员的额度

**Comment by sinopec** [comment]
同样得问题，渠道额度为0之后没法再用了

**Comment by Calcium-Ion** [comment]
渠道的额度和系统限制没有任何关系。这只是一个显示而已，有的渠道不支持获取剩余额度就会一直显示为0

**Comment by Calcium-Ion** [comment]
使用不了请检查用户额度和令牌额度

**Comment by sinopec** [comment]
> 使用不了请检查用户额度和令牌额度

还有一个用户额度管理没注意，更新后已好，感谢。。。。

**Comment by padoru233** [comment]
渠道额度用完了就没法使用了，不知道如何获取的额度，还不能更改，我这个渠道是按次收费的
{
  "error": {
    "message": "token quota is not enough, token remain quota: ＄0.250000, need quota: ＄5.500000 (request id: 20250903003241616637594M0nCmn54)",
    "type": "new_api_error",
    "param": "",
    "code": "pre_consume_token_quota_failed"
  }
}
