### ISSUE TITLE
text-moderation-latest 不计费

### ISSUE THREAD

**Issue by AidenYu0229** [Calcium-Ion/new-api#68]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
图1为newapi 图2为原版oneapi
**复现步骤**
并发测试了上千条
**预期结果**
希望和oneapi计费保持一致
**相关截图**
<img width="1022" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/140964833/25199b98-d030-4045-b8ee-7c9fb1558057">
<img width="715" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/140964833/c4737c29-4143-42f5-a052-5213e1eebde4">

**Comment by Calcium-Ion** [comment]
我这边测试时是有计费的，可以的话提供一下能复现的请求体。 
<img width="871" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/61247483/f630158b-9362-4d26-ba1a-fb744599b966">
