### ISSUE TITLE
PgSQL数据库下令牌Key异常

### ISSUE THREAD

**Issue by tempppabx1** [Calcium-Ion/new-api#682]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
全新安装，最新版本new-api使用PgSQL数据库查询/调用令牌时报错，内网的报错后又尝试了第三方的的远程PgSQL数据库，依然相同报错
查询令牌时报错，但好像不影响查询结果
```/build/model/user.go:511 ERROR: syntax error at or near "group" (SQLSTATE 42601)```

调用令牌时报错，无法调用
```
/build/model/token.go:166 ERROR: syntax error at or near "=" (SQLSTATE 42601)
 
[rows:0] SELECT * FROM "tokens" WHERE `key` = '*****' AND "tokens"."deleted_at" IS NULL ORDER BY "tokens"."id" LIMIT 1

[ERR] user 0 | 无效的令牌 
（***是查询的Key，我尝试在数据库客户端里执行了相同命令也有报错，怀疑是创建PgSQL时候表的结构有些问题）
```
**复现步骤**
查询/调用令牌

**预期结果**
正常调用

**Comment by DarremMolko** [comment]
I'm experiencing the same issue.
![Screenshot_20241230-145810](https://github.com/user-attachments/assets/0c3ec87d-9927-4a59-b582-5e258a5c1c61)
