### ISSUE TITLE
微信注册没了

### ISSUE THREAD

**Issue by yuanjie-ai** [Calcium-Ion/new-api#7]
![image](https://github.com/Calcium-Ion/new-api/assets/20265321/da30f4eb-1b75-45bf-a452-48b6282d1d18)
<img width="714" alt="image" src="https://github.com/Calcium-Ion/new-api/assets/20265321/76814955-bfc9-40a9-ac8b-a5283d6fbe1d">

**Comment by Calcium-Ion** [comment]
之后会修复，建议先用one api

**Comment by jinhuili-lab** [comment]
修一下微信登录吧，发验证码的话不是很方便。扫码关注之后登录成功，这样的体验最佳

**Comment by Calcium-Ion** [comment]
好的，您加群了吗，可能需要您协助测试

**Comment by jinhuili-lab** [comment]
加了，私聊你了

**Comment by jinhuili-lab** [comment]
HI
