### ISSUE TITLE
Newapi能加个渠道适用所有的用户组吗

### ISSUE THREAD

**Issue by mmw1984** [Calcium-Ion/new-api#71]
![IMG_20240207_174727](https://github.com/Calcium-Ion/new-api/assets/103017331/1bff2ae9-798e-425e-af5f-e1f80f63e621)
![IMG_20240207_174718](https://github.com/Calcium-Ion/new-api/assets/103017331/46a4103c-9ae7-445c-a4c9-48eb78e6c6d3)

**Comment by longkun0203** [comment]
支持自定义哪些用户组的
