### ISSUE TITLE
渠道多了容易管理混乱

### ISSUE THREAD

**Issue by Passerby1011** [Calcium-Ion/new-api#72]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
渠道多了容易管理混乱，同一个模型可能很多渠道都有，时间一长管理起来非常的坐牢，因为记不住那些渠道有什么模型。希望可以在渠道界面加个模型筛选
**应用场景**
方便同一模型的多渠道管理

**Comment by Calcium-Ion** [comment]
添加了简单的模型搜索
