### ISSUE TITLE
用户可以注销用户在重新注册撸赠送额度

### ISSUE THREAD

**Issue by h1xy** [Calcium-Ion/new-api#75]
发现有用户注销账号，在重新注册就可以再次获得赠送额度。one-api应该已经fix了这个问题。能否改为同一个邮箱仅赠送一次。

**Comment by Calcium-Ion** [comment]
应该没有这个问题的了吧？之前就修复过了

**Comment by dingeral** [comment]
应该没修好，我还在嫖
