### ISSUE TITLE
mj功能请求 已star

### ISSUE THREAD

**Issue by duansix** [Calcium-Ion/new-api#85]
对接上游new api
在渠道管理中添加渠道，渠道类型选择Midjourney Proxy，模型选择midjourney
地址填写上游new api的地址，例如：http://localhost:8080/
密钥填写上游new api的密钥
------------------------------------------------
上游返回的图片地址为https://test.com/mj/image/1709524067178581（test.com是上游的地址）
实际测试 我的站点 https://abc.com/mj/image/1709524067178581 也是可以实现访问图片的
能否将 绘图页面的 查看图片按钮 是自己站点的地址 而不是上游的图片地址 （如果上游的域名有广告 会丢失客户）
还有就是API返回的图片链接 也替换成自己的站点地址

**Comment by Calcium-Ion** [comment]
近期会解决

**Comment by Calcium-Ion** [comment]
现在应该原本就是替换成站点的图片地址，管理员看到的才是上游地址才对，你用普通用户的账号测试一下？
