### ISSUE TITLE
对于使用Mysql的情况下，从v0.1.x更新到v0.2.x无法启动的问题

### ISSUE THREAD

**Issue by Calcium-Ion** [Calcium-Ion/new-api#87]
需要手动删除索引。  
```sql
DROP INDEX idx_channels_key ON channels;  
```
或者备份数据库数据后，删除channels表重新生成，再导入数据

**Comment by hcppxgit** [comment]
小白请问一下使用SQLite数据库，用宝塔部署的，怎样删除这个索引啊，感觉是不是要把数据库下载到自己电脑，再找个工具来执行这个命令？

**Comment by Calcium-Ion** [comment]
> 小白请问一下使用SQLite数据库，用宝塔部署的，怎样删除这个索引啊，感觉是不是要把数据库下载到自己电脑，再找个工具来执行这个命令？

sqlite数据库可以直接更新，不需要操作
