### ISSUE TITLE
国内模型messages.role.system的支持

### ISSUE THREAD

**Issue by fengjisheng** [Calcium-Ion/new-api#89]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
大部分国内模型messages.role都已经支持system, 只有少数支持, 某些场景比如角色扮演, 需要系统角色指令 +上下文回答.
看代码部分渠道都做了角色转换, 导致无法锁定系统角色正确的回答问题. 总是跳出规则变成其它不相关的答案.

百度文心, 智普AI V4版, 讯飞星火3.5 这些都已经支持system角色参数.

**Comment by Calcium-Ion** [comment]
可以加群详细说一下吗
