### ISSUE TITLE
大佬你好，自动禁用未开启，设置里面的响应也设置了超过30秒，还是会自动禁用，没有配置环境变量这些，好像是设置没有生效

### ISSUE THREAD

**Issue by homestoo** [Calcium-Ion/new-api#9]
[](url)**例行检查**
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
大佬你好，自动禁用未开启，设置里面的响应也设置了超过30秒，还是会自动禁用，没有配置环境变量这些，好像是设置没有生效

**预期结果**

<img width="401" alt="B03AF13A6A6312E76C6291E2CE71596F" src="https://github.com/Calcium-Ion/new-api/assets/95828857/b388fcbc-1044-4f12-a3cb-263a898546cb">

**Comment by Calcium-Ion** [comment]
这是one api原版项目的遗留问题，这边的下个版本会修复这个问题
