### ISSUE TITLE
請求Anthropic Claude API的時候發生問題: prompt: Field required

### ISSUE THREAD

**Issue by ckt1031** [Calcium-Ion/new-api#94]
**例行检查**

+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

請求API的時候發生問題: `prompt: Field required`。

**复现步骤**

添加這個API到頻道之中,並進行測試和實際進行請求。

**相关截图**

![image](https://github.com/Calcium-Ion/new-api/assets/65409152/bb9e332a-59d0-425e-9a09-09bba049133c)

**Comment by Calcium-Ion** [comment]
可以加群提供一下测试key吗

**Comment by ckt1031** [comment]
> 可以加群提供一下测试key吗

本人沒QQ, 僅有的電話號碼也註冊失敗😨, 有沒有其他可連繫的方式

**Comment by Calcium-Ion** [comment]
> > 可以加群提供一下测试key吗
> 
> 本人沒QQ, 僅有的電話號碼也註冊失敗😨, 有沒有其他可連繫的方式

没事，群友提供了，正在测试
