### ISSUE TITLE
stream模式在上游返回错误的情况下仍然扣费

### ISSUE THREAD

**Issue by ArcaneWhispers** [Calcium-Ion/new-api#95]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

上游渠道无余额、上游渠道key错误、或者上游渠道地址填错等只要是上游渠道错误，都会造成stream流式请求返回内容为空，并且令牌会扣费。stream设为false就没问题。

Docker部署最新版很容易就能测出来，这个bug应该存在一周以上。

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
最新提交已修复

**Comment by ArcaneWhispers** [comment]
> 最新提交已修复

效率，赞
