### ISSUE TITLE
删除用户后，该用户令牌依然在数据库中

### ISSUE THREAD

**Issue by ArcaneWhispers** [Calcium-Ion/new-api#97]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

用户被硬删除之后，该用户创建的所有令牌都在数据表中，无法被自动删除。

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by Calcium-Ion** [comment]
是这样设计的，防止新的用户生成的令牌和被删除的用户一样，导致key盗刷
